### ISSUE TITLE
Reconfirm S vocab

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1000]
Check to see if it's an accurate reflection of the actual properties/classes/etc. in use.

**Comment by jimsafley** [comment]
All modifications to the data model should be reflected in this repository: https://github.com/omeka/omeka-s-vocab

**Comment by jimsafley** [comment]
The last commit to omeka-s-vocab was Oct 27, 2016. According to our migration dates, the data model hasn't changed since then. I've looked over the serialization and have found no omissions, so I think that reconfirms the Omeka S vocabulary.

There are some `@todo`s in the vocab that I'll look into:

- Clarify comments
- Add rdfs:subClassOf, rdfs:subPropertyOf, owl:equivalentProperty, owl:sameAs where needed

**Comment by patrickmj** [comment]
Since we don't really use those rdfs and owl properties elsewhere, would it be more consistent to leave them out?

**Comment by jimsafley** [comment]
I don't think there's an reason for our vocabulary to be consistent with the features we provide. All other vocabularies we consume use rdfs and owl for descriptive purposes.
