### ISSUE TITLE
Resource template datatype dropdown disappears in FF when zoomed in

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1001]
When zoomed in, the dropdown for selecting a datatype for a property in a resource template disappears.

![datatype](https://user-images.githubusercontent.com/153262/28581159-8f6bd118-712f-11e7-94bd-26c53ed2b754.png)

**Comment by jimsafley** [comment]
This is similar to what I'm seeing in Chrome. Some of the data type select options get hidden under the fold in the sidebar. Oftentimes it's impossible to scroll to the last few options. At that point there are three scrollbars next to each other.

**Comment by kimisgold** [comment]
In Chrome at 125% zoom, I see a scrollbar for page content and a scrollbar for sidebar content—Firefox only scrolls the page content, so I'll look into why. 

@jimsafley Theoretically, the chosen select plugin creates extra room at the bottom of select's container so that the dropdown menu is visible. Another developer offered [this modification](https://github.com/harvesthq/chosen/issues/155#issuecomment-173238083) on top of chosen core that I think allows the menu to appear above the select—if you think this looks promising, I can help you style it if you implement the JS.
