### ISSUE TITLE
When editing an item, padding for Item Sets sidebar label different from other sidebars

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1018]
In both FF and Chromium:

![itemsetsidebar](https://user-images.githubusercontent.com/153262/29043076-9c7aa4b2-7b87-11e7-81e9-1472020bf92b.png)

![mediasidebar](https://user-images.githubusercontent.com/153262/29043094-a7f15c6e-7b87-11e7-95e4-4a2a3753fd27.png)

**Comment by kimisgold** [comment]
Should be fixed in https://github.com/omeka/omeka-s/commit/3d704a1b01c042671fa790b9b757da028e77da92. Can you pull and confirm?

**Comment by patrickmj** [comment]
Yep! Looks good to me.

I'm going through my modules adding the `<div class='sidebar-content'>` Anything else that I need to change for the same kind of issue?

**Comment by kimisgold** [comment]
Please don't add `.sidebar-content`: that should only be used for dynamically-loaded content. For sidebars using `.confirm-panel`, the immediately preceding sibling should have `.confirm-main`.

**Comment by patrickmj** [comment]
So, where should I use `.confirm-panel`? I'm not really confirming anything. Instead, the CSVImport sidebar adds mapping details about the column being mapped.

**Comment by kimisgold** [comment]
I'd look at sidebars that use `.confirm-panel`. The resource template property edit sidebar is a good example: it includes fields for user changes that must be confirmed by the 'Set changes' button sticking to the bottom of the sidebar. If CSVImport doesn't have a button like that, don't worry about it. I only mentioned `.confirm-main` with regards to sidebars already using `.confirm-panel`.

**Comment by zerocrates** [comment]
@patrickmj: Kim previously made some changes with pretty wide-ranging effects (and side effects) to try to fix another problem (the problem with the resource template sidebar). She just rolled those back and fixed that problem another way, so that's probably what caused, and then fixed, this problem you were seeing.

As Kim says, if you're not using sidebars with this specific pattern (a button taking the full width of the sidebar pinned to its bottom), you shouldn't need to change anything. Other sidebar stuff being broken in some way would be different problems.

**Comment by patrickmj** [comment]
Reverting my earlier stuff and a new pull on core seems to make everything happy. Thanks!
