### ISSUE TITLE
Make it less annoying to generate hyperlinks with HTML content

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1025]
1. **`link()` and image markup**: The `link()` method is structured so that it cannot output image markup, making the task of wrapping both an image and string with a link pretty annoying. This is roughly what we're doing now in sidebars with selectable item resources:

    ```
    <a href="#" class="select-resource">
        <img src="<?php echo $escape($media->thumbnailUrl('square')); ?>">
        <span class="resource-name"><?php echo $escape($item->displayTitle()); ?></span>
    </a>
    ```

**Comment by zerocrates** [comment]
The general problem behind 1 is that we don't have any way to do links that don't always escape the link text, so we can't put markup in them.

This one's kind of a special case because it's doing a `href="#"` anyway, but still.

There's actually a couple of levels here: the length of the code used to print the thumbnail `img` is equally problematic I think. Not using a helper here makes it trickier to handle stuff like `alt` as well.

**Comment by zerocrates** [comment]
I've addressed part of this with a new view helper, `thumbnail`. As of right now it defaults to blank `alt`, as that really seems appropriate for most of our usages of thumbnails, but that can be changed if we think there's some more suitable default.
