### ISSUE TITLE
How does the new local store configuration affect CheckDirPermissionsTask?

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1059]
Users can now set the local store's `base_path` in configuration (via #1056). During installation `CheckDirPermissionsTask` checks whether the "/files" directory is writable. Shouldn't it first check if a `base_path` was set? If so, would this resolve #501?

**Comment by zerocrates** [comment]
We _probably_ should have it check the base_path, whatever it is, yes. Realistically it's not going to come up very often and people using this feature are less likely to need the installer prodding them to make the directory writable, so we could get away OK without it, but it'd be kinda crummy to do so.

It wouldn't affect #501 because that's about a process that's happening on every load (or every use of the store, actually), where this would only affect the installer.

**Comment by jimsafley** [comment]
#501 does ask if the check should be on install.

**Comment by zerocrates** [comment]
I think it's the "only" that's supposed to be the key word there. Meaning, fixing #501 is mostly about just _removing_ the check from the store's startup, and instead just having it try to do its work and throw an exception on failure.
