### ISSUE TITLE
Behavior of Add New Media dropdown

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#109]
Choosing a media type pushing the dropdown down below the newly added field. This can result in it being in the middle of previously and newly added media fields. Should it work like this? Should the dropdown always remain at the top. Should previously added media be set off with a header or by color?

**Comment by jimsafley** [comment]
I think the add media dropdown should remain at the top. That way there's no confusion where it is, even on the rare occasions when the media types push down below the fold.

**Comment by zerocrates** [comment]
If the "adder" stays on top, then i'd want to see the new media inputs get pushed in right below it, not at the bottom of the whole list (so, when you add more than one, they'd end up in "reverse" order).

Otherwise, each added media's input would appear further and further away from the "Add New Media" control.

It's also possible that we don't need so much horizontal space for the "add new media" control since it's very simple, or that we could use the huge empty space where the sidebar should be for this or some other purpose on this tab.

@kimisgold, your opinion would probably be pretty valuable on this

**Comment by kimisgold** [comment]
I like the idea of moving the add media input to the sidebar. It'd be fixed, always available, and we could always scroll down to the new file if it's being added to a long list of existing media.

Relatedly, I think there could be use for making media order sortable, especially in context of designating a different primary media file. Alternatively, we could leave media order as is, but also provide the option to designate a primary media file irregardless of order position.

**Comment by jimsafley** [comment]
I like the sidebar idea.

I'd rather set a primary media than introduce media order.

**Comment by zerocrates** [comment]
The one thing about order is that it's something Omeka 2 has, so that may play into the decisionmaking process of whether to have it in S (especially if we're already going to have to introduce a column for storing whether something is the "primary" one anyway)
