### ISSUE TITLE
Small issue with asset in site settings

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1105]
I had a directory "CenterRow", I set an asset as logo and all be fine, the logo is displayed. Later, I renamed the directory in lower case "centerrow". So my logo disappeared and I cannot set a new one (but other params were available). 

In fact, in the database, the name of the site setting stayed `theme_settings_CenterRow`, so as mysql is not case sensitive, it finds it, but somewhere else, it should be `theme_settings_centerrow`, so the asset cannot be saved.

**Comment by zerocrates** [comment]
The problem is going to be that we get all the settings once and hold them in memory, so even though MySQL cheerfully knows that two differing only in case are the same, we're using PHP-based lookup which doesn't.

One simple solution would be to strtolower the settings keys, either when setting (which would avoid the problem in the future but wouldn't actually fix _your_ specific case of it) or when "caching". We could also set MySQL to be case-sensitive with the setting names which would also fix it, but I'm not sure that's a wise course of action here.

**Comment by Daniel-KM** [comment]
For now, I prefer to remember this point in a list of issues to be resolved manually.
