### ISSUE TITLE
Item sets not attached to a site are displayed inside it.

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1176]
In Omeka S, it is possible to attach item sets as resources of a site. Nevertheless, even the not-attached item sets are displayed inside the site, once the id is known, or indirectly via the list of item sets of an item. So is there a param to filter item sets attached to a site to display only the selected one and the same for the metadata of items?

**Comment by zerocrates** [comment]
Since this issue was filed, we've done a little bit to address this: most relevantly, we have the feature that sets a `noindex` meta-tag on non-attached item, item set and media pages. So to the extent the concern is with spurious search engine results, that's a resolution to the problem.

The aspect about item set attachments not being respected when we display the item sets for an item on its show page, we have a separate issue for that: #1724.

Those together would close off much of the organic pathways to having these "out of bounds" references. As for the situation of just a user manually inputting a URL to an "out of bounds" set (or other resource): that would probably be a separate feature to make those request attempts 404. Any such feature would need to be an opt-in, though.
