### ISSUE TITLE
On media/show should there be links to file formats?

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#118]
eg, should there be a link to the original file, the various thumbnails, etc?

**Comment by kimisgold** [comment]
We have them available in Omeka Classic, and they don't strike me as something we should take away in S.

**Comment by zerocrates** [comment]
the answer is yes, we should have them.

one slight wrinkle to be aware of in S vs "classic": in addition to needing a check for whether this media has thumbnails, you also need to check if it has an original, since that's optional for all media. A given media can have an original, thumbnails, one or the other alone, or neither.
