### ISSUE TITLE
User's default template doesn't fill in class

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1192]
Via forums: https://forum.omeka.org/t/problem-with-user-default-resource-template/5344

When you set a default resource template for a specific user and then you add an item with that user, suggested class from the template is not applied to the class of that item.

**Comment by zerocrates** [comment]
This is probably happening due to earlier changes that were made to ensure that the template's class choice didn't override the already-saved class on an item.

Before the "user default template" feature, we could use the fact that the template was set at page load time as a heuristic for it being a pre-existing item, and I believe in that case we explicitly disable setting the class. Of course with the new feature, that heuristic is no longer accurate.
