### ISSUE TITLE
 Folksonomy doesn't allow to use tag with quotes Omeka S Modules

### ISSUE THREAD

**Issue by Falteri** [omeka/omeka-s#1201]
When you edit an item and you try to get tags from the right panel (Folksonomy), this is not possible if the tag contains single quotes (I suppose the same issue with some other special characters).

**Comment by zerocrates** [comment]
Hi, Falteri,

This is the issue tracker for the core of Omeka S. For modules, you're going to want to post issues on the specific Github site for the module you're dealing with (not least because in this case, the Folksonomy module has a different developer than Omeka S itself does). 

The Folksonomy module's issue tracker is here: https://github.com/Daniel-KM/Omeka-S-module-Folksonomy/issues
