### ISSUE TITLE
On items/show should Linked Resources tab only appear if there are linked resources?

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#121]

**Comment by patrickmj** [comment]
I think that entire tab should be folded into the main metadata page for a resource. It's an artificial distinction.

**Comment by zerocrates** [comment]
>I think that entire tab should be folded into the main metadata page for a resource. It's an artificial distinction.

I'd assume that would really mean just dropping the linked resources tab rather than folding anything in. I don't see how you could merge the "reverse" links, where the current Item is the object, into the regular value display, short of actually figuring out the inverse property and that's not going to happen.

**Comment by patrickmj** [comment]
Yep. I mean getting rid of that tab.

**Comment by zerocrates** [comment]
- keep the tab
- add a label when it would be blank
