### ISSUE TITLE
Fix install and use with new default mysql mode "ONLY_FULL_GROUP_BY"

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1216]
Since mysql 5.7.5, the mode "ONLY_FULL_GROUP_BY" is enabled by default. This is not yet the case for MariaDB, but there are some requests for it. 

With this mode, Omeka S does not install. It throws: 
```
An exception occurred while executing 'SELECT p0_.id AS id_0, p0_.local_name AS local_name_1, p0_.label AS label_2, p0_.comment AS comment_3, p0_.owner_id AS owner_id_4, p0_.vocabulary_id AS vocabulary_id_5 FROM property p0_ INNER JOIN vocabulary v1_ ON p0_.vocabulary_id = v1_.id WHERE v1_.prefix = ? GROUP BY p0_.id ORDER BY p0_.id ASC' with params ["dcterms"]: SQLSTATE[42000]: Syntax error or access violation: 1055 'omeka_s_test.p0_.local_name' isn't in GROUP BY
```

And if we upgrade an installed version, it doesn't work either on some pages. For example, the sites cannot be listed because the query is invalid:
```
SELECT id, slug
FROM site
GROUP BY id;
```

For a quick fix, the solution is simple: just remove this mode. 
```
SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''));
```

But in fact, `group by` is used in only one place in the core: https://github.com/omeka/omeka-s/blob/develop/application/src/Api/Adapter/AbstractEntityAdapter.php#L209. So when this line is removed, Omeka S installs and works fine. There may be some issues on some Omeka modules nevertheless, but `group by` is not used often.

So there are two solutions: 
- remove the line 209 and fix the issues in some modules;
- don't support this mode.

I didn't check for Omeka Classic yet, but the issue will probably occur too.

**Comment by zerocrates** [comment]
We already force the mode in Classic.

I'll have to look into this a little more, because I'm pretty certain we're already running with ONLY_FULL_GROUP_BY in testing and normal operation here and aren't seeing this problem.

**Comment by zerocrates** [comment]
Simply removing the groupBy is likely to cause duplicate results all over the place in browse pages where the filters specify a join, like searching on values where more than one value matches the query.

**Comment by zerocrates** [comment]
Our prior discussion on this topic is #712

**Comment by Daniel-KM** [comment]
I try on a fresh install with the mode and it fails. I'm checking other modes.

**Comment by zerocrates** [comment]
@Daniel-KM is this a MySQL 5.7.5+ install, or did you enable the mode on an older version? I do remember that older versions are actually stricter with that option set than 5.7 actually is (5.7 will allow any column that's functionally dependent on the grouped column, which should be the case here).

**Comment by Daniel-KM** [comment]
I just discover the issue. I use generally MariaDB that don't set it by default, but I have a server to upgrade for a client who uses Ubuntu, and it fails, and this is the way I fix it (remove the mode).

**Comment by Daniel-KM** [comment]
So I try to enable the mode on MariaDB.

**Comment by zerocrates** [comment]
We'll have to do more checking on our end but my recollection is that what we've got works under the default mode setting on 5.7.5+.

It probably _wouldn't_ work with ONLY_FULL_GROUP_BY set on older MySQL versions, and I don't know the status with MariaDB. Do you have any info on what server/version your client's server that showed the problem was using?

**Comment by Daniel-KM** [comment]
It was an upgrade to Ubuntu 16.04.3 LTS / mysql  Ver 14.14 Distrib 5.7.21. But there were many modules installed, so the issue may be related on them, because many pages worked.

Then I try the current testing version on Debian (mariadb  Ver 15.1 Distrib 10.1.29-MariaDB) and set the mode on, and it doesn't work.

**Comment by zerocrates** [comment]
Ah, I could see it being a module.

We'll have a bit of a decision to make about what it makes sense for us to do in core if this is only an issue with non-standard configurations (assuming that's the case).

**Comment by Daniel-KM** [comment]
I find that the module Search doesn't work with this mode on in the Ubuntu server, but this module doesn't use `group by`, except via the api manager for a standard search. 

And I'm trying to add the mode in MariaDB, because some db specialists recommend it.

**Comment by zerocrates** [comment]
OK, that's helpful information.

It does make sense that the problem could happen to modules just using the normal adapter search because of the groupBy there. Taking it away could work and help limit the scope of people needing to know about this behavior, but it would have to be added back in places like the resource entity adapter, at least. 

Really, anywhere with to-many joins would probably need to add `groupBy` if it were taken out of the default search method. I don't want to just remove the mode either, though, if it can be reasonably avoided.

Turning on ONLY_FULL_GROUP_BY in pre-5.7 MySQL (I don't know the MariaDB situation but I suspect it's similar) is _much_ more restrictive than in 5.7.5+ and I'm not sure I see us doing a lot to support that. The functional dependency support generally allows us to group by ID and use our usual patterns, with sorting being the main area where tweaks have had to be made.

As for the problem with Search and 5.7, I don't immediately see anything that would do it in Search, though I do see a potential area for that in Solr. If you're seeing that specific problem and could provide the error message (and therefore the offending SQL) that would be helpful for figuring what kind of changes could be made on either side, core or module.

**Comment by Daniel-KM** [comment]
I can't downgrade the Ubuntu server, but I just reenabled the mode for quick checks, and it works fine nearly everywhere, even in the Search module. I see a issue with a specific module, but it can be fixed. So it's better not to change core.

**Comment by zerocrates** [comment]
Thanks for following up.
