### ISSUE TITLE
Sql index for the columns value and type in table value

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1252]
Is there a reason why there is no sql indexes for the columns value, type or even uri in the table value?

**Comment by zerocrates** [comment]
One of my own personal installation has had indexes on `value` and `uri` since far back when when we would have been working on the data model more, so I'm tempted to say it's basically just an oversight.

type, value, lang, and uri are all probably reasonable to index.

**Comment by zerocrates** [comment]
Okay, so I _did_ add the value and uri indexes at some point... I'll have to get back to you on this one. There's clearly an inconsistency floating around somewhere.

**Comment by zerocrates** [comment]
This is just my own misremembering: we _do_ have indexes on value and uri (that would be _quite_ the oversight to not have indexing at all here).

We have to do these indexes outside the normal Doctrine system because Doctrine doesn't provide us a way to do size-limited indexes on these fields, but size-limiting is required for the indexes to be legal. So, there's an event that's used to just manually specify the SQL for the value table: Omeka\Db\Event\Listener\CreateTableOverride.

Funny the things you can forget in 2 years.

**Comment by zerocrates** [comment]
As a final note, if you don't _actually_ have indexes on `value` and `uri` in your value table, then that's an issue specific to your install (we do have them in the install sql and they were added in a migration back when they appeared as well).

Of course, we can look at indexing type (and possibly lang) as well.

**Comment by Daniel-KM** [comment]
Thanks you very much for all your notes. Yes, most of my installs have it, not the one that I checked before posting this issue, neither the entity, but it is in the main schema.sql, so there is no issue except if you want to add some indexes.
