### ISSUE TITLE
Consider extending Zend\Form\Form to include the serviceLocator

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1254]
Often enough when I'm creating a form, especially a configuration form for a module, I end up needing to create a factory to inject the service (usually just the global settings).

Does it make sense to create our own extension to always let the serviceLocator be in our forms like they are elsewhere (e.g. Module)?

**Comment by zerocrates** [comment]
We've pretty much been trying to keep to the current Zend pattern of not accessing the locator directly... we cheat a couple places but I don't think in general we want to expand those places...

The idea is that keeping the locator itself out of the actual end users makes them more reusable. For example, components can just pass dependencies along directly to create new or sub-components, rather than having to go through the locator to do that, you have more flexibility in switching out or changing the locator itself in the future, and testing becomes much simpler (check out the awful nonsense we have in the tests where we're working with stuff that uses the locator directly).

It also means you end up with things like typehints and `use` statements in the consumers, which usually ends up being an easier way of tracking dependencies than looking for the service string that's passed to the locator.

In your specific case, are you talking about an actual config form, as in the kind that you get from the Module page? For that situation I would imagine you could just handle the "set the defaults from the Settings" part outside of the Form class itself, in the module class's config form method where you can more simply get the settings.
