### ISSUE TITLE
Test batch edit user update

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1295]
Branch is batch-edit-users.

Batch editing should work pretty much the same as for other things. You'll note a couple differences, the current user is treated specially and excluded from batch editing, and there's a new "advanced search" for users.

A particular area of interest is the stuff dealing with site permissions here: I think we might have some issues with the current labeling, and perhaps some issues with overcomplexity of the batch edit form pieces that deal with updating site permissions.

**Comment by zerocrates** [comment]
@Daniel-KM:

It seems to me that "Remove from site permission" could be merged into the "Add to site permission as" dropdown as a choice like "[Remove]". That way there'd only need to be one "site picker" on the batch edit page, and I think we could make it a little clearer that way. Does that make sense to you?

**Comment by Daniel-KM** [comment]
Not sure if I understand. The admin may wants to remove the users from many sites, and add them from many other sites. If "remove" is only a choice, the users will be removed from all sites. The fields are similar for items (add/remove item sets).

**Comment by mebrett** [comment]
Everything is functional.

I would change the label from "activity" to "status" since that's a better fit with what we're setting there. 

I like having site permissions broken out into adding and removing, but the phrasing is a bit off. "Remove from site permissions" might work better as "Remove site permissions for" - we're acting on the user, after all. Similarly, "Add site permissions for [the following sites]"

In terms of interface, the dropdown which allows you to select multiple times was a little confusing at first. I thought I would only be able to select a single site. I can make it clear in the documentation that you can select as many as you want, but we may want to add helper text saying "You can select multiple times" or something to that effect.

**Comment by zerocrates** [comment]
Yeah. On the dropdown, as Daniel says, it's the same interface as is currently used for changing Item Set assignments when batching items. Do we have any guidance there?

**Comment by mebrett** [comment]
Not at the moment: 
![screen shot 2018-09-04 at 11 02 18 am](https://user-images.githubusercontent.com/2314070/45039647-04316700-b032-11e8-97a5-91005e533775.png)
