### ISSUE TITLE
Purpose of exposing json-ld resource by default

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1306]
In all pages resource pages, admin or public, the json-ld of resources are exposed (https://github.com/omeka/omeka-s/blob/55576ea9657f8b3a8cb2f6e8918de431996ce4a5/application/Module.php#L105-L131). What is the purpose of it? If it's required, can it be made optional? 
And the module HideProperties doesn't work with it, so may be dangerous if there are sensitive data inside properties.

**Comment by Daniel-KM** [comment]
Ideally, there should be a data somewhere to set each property public or private, at least via the resource templates.

**Comment by Daniel-KM** [comment]
The same issue occurs in the api end-point too.

**Comment by zerocrates** [comment]
I don't think the templates will work well for this, because it would get quite complicated to involve them in the search process properly to avoid private values being discoverable through searching and checking which results are returned.

The only feasible way I can think of to handle that would be an actual private flag on the value table itself. Templates _could_ manage the default state of that flag, I suppose.

The JSON-LD gets included on the pages for the purpose of machine-readable metadata discovery... JSON-LD explicitly specifies that data can be included in this way in a `script` tag with the appropriate type. The idea is something like the old Coins plugin, but that supports the RDF-esque data of S more robustly. It _could_ be made to be something that can be disabled, but I think the issue of value "privacy" really goes beyond that inclusion (as you say, the exact same data is available in the API, or discoverable via a search as I mention above).

**Comment by Daniel-KM** [comment]
So it will be fine if it can be made optional on public pages, at site level. I have a site with a specific mobile theme, and it is too heavy in that case. Coins (that was ported https://github.com/biblibre/omeka-s-module-coins) is light, since it doesn't list all metadata. It's always possible to remove them by the events, but it would be better if the json is off by default.

And for the admin page, I don't understand the purpose, since all pages are created via server, so there is no need to store the json in the page. And currently, I don't see a module that use it. And in that case, it can enable the output.

The privacy is not related, but is important too. In fact, generally, it is property related, not value related: there are always some fields that the librarians have to keep confidential. Perhaps some people want to manage it at value level, but I don't know.

**Comment by kloor** [comment]
For items with a lot of linked data, I've discovered that the JSON-LD is the main culprit for performance problems both in time it takes to fetch and the size of the resulting HTML. This is in particular while browsing. While I'm not concerned about privacy of the data, I am currently considering the advantage of the JSON-LD versus the impact it is having on the user experience.

**Comment by Daniel-KM** [comment]
An intermediate solution (but probably useless) would be to give a link to the api url for each item.

**Comment by zerocrates** [comment]
Since we've merged both value privacy as a feature (addressing the root of the privacy-based issue here), and configuration settings for disabling the JSON-LD embedding (more addressing the performance/size aspect), I'm going to call this closed.
