### ISSUE TITLE
Add Vocabulary by URL / Namespace

### ISSUE THREAD

**Issue by milnerm** [omeka/omeka-s#1327]
Any chance we could use a namespace definition URL etc for adding a vocabulary, rather than downloading it, and uploading it again to add a new vocabulary? I appreciate the need for custom vocabularies, but I find it puzzling in terms of LOD why uploading a local file is the only option for adding a new vocabulary to Omeka S when the aim for many of us is to use existing namespaces.

See forum at https://forum.omeka.org/t/adding-vocabularies/7323 for original request.

**Comment by zerocrates** [comment]
Import via URL is certainly a possibility... in terms of the reasoning behind what we have, the local-file implementation is used internally by the installer; it's where the initial vocabs that come with an S install come from. The uploader as the interface for users was chosen because it supports both pre-existing and custom-created vocabularies both with relatively equal ease.

**Comment by milnerm** [comment]
That makes sense to me. Mind you the root of the issue is also the fact that something is preventing the installer from adding those initial vocabs (which I've noted in a forum ticket, and would be another issue on here). Still, if everything is defined in the online version of the vocab, would be nice and smooth to just plunk in a URL, and go.

**Comment by jimsafley** [comment]
A point of clarification: the namespace URL hardly ever resolves to an RDF vocabulary file. These files are sometimes hard to locate and, from past observation, are prone to roaming or disappearing altogether. This is why we store our default vocabularies locally. Even so, your idea is a good one. We should allow users to import vocabularies directly from URLs.
