### ISSUE TITLE
Cannot upload information to a class after 73 registers.

### ISSUE THREAD

**Issue by hydrosIII** [omeka/omeka-s#1330]
Currently we are using the bibo:authorlist to index names in the documents. Some documents have a lot of names, so we have a problem after uploading 73 registers. After that number it throws an error. It throws a "CRSF error: Value requires and cannot be empty"
![captura de pantalla de 2018-10-29 13-59-52](https://user-images.githubusercontent.com/7807363/47677240-39ff5180-db84-11e8-8f74-b842e1447be8.png)

**Comment by Daniel-KM** [comment]
I have the same issue with one of my modules (the config form of [Reference](https://github.com/Daniel-KM/Omeka-S-module-Reference), that failed when there are too many vocabularies), so I added a js to catch the click on the button, to convert all the user inputs into a json, then the json is reconverted by the controller (or the form). It's something to be implemented, because not all people can change php settings. And it can be done easily with the warn when form is changed, that uses already a similar check.

**Comment by symac** [comment]
This issue might be expanded to other cases where posted data is truncated and generates a CSRF issue. I just encountered it with an item that has more than 800 medias attached (JPG). It took me some times to understand that this CSRF was related to truncated data. 

If it's not possible to change the way ```_POST``` is constructed or to intercept this issue, it would at least be great to have a link to a documentation page explaining the possible origin of this issue, with the ```max_input_vars``` hint (increasing it from 1000 to 1200 in my .htaccess file did the trick for me)

**Comment by zerocrates** [comment]
Yeah, something in the realm of what Daniel mentioned (more or less, submitting the form as one big JSON payload) is probably the way to fix this issue. The downside is that Javascript would be required for submission to work... but it's already required in a practical sense all over the place on the admin panel.

Detecting it is actually somewhat difficult due to the way PHP handles this: it just truncates the variables before we see them and emits a warning.
