### ISSUE TITLE
Impossible to get a module by api

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1379]
How to get a module by api: 

```php
$module = $this->api()->read('modules', $moduleName)->getContent();
```
It doesn't work: it has not ResourceInterface required in https://github.com/omeka/omeka-s/blob/develop/application/src/Api/Manager.php#L261, and it cannot be searched one by one, even if there is a search and read methods in the adapter, and the id is a name anyway, not a `0` (https://github.com/omeka/omeka-s/blob/develop/application/src/Mvc/Controller/Plugin/Api.php#L82).

**Comment by zerocrates** [comment]
I don't see an error with getting modules from the API... both "browsing" and "reading." At least it works in the API itself, I didn't check using the internal helper but just using the REST interface. The Module class does implement ResourceInterface... and the ID being a name doesn't really matter (the zero in searchOne being just an index into a standard array, not a reference to an ID, since basically nothing has zero as an ID anyway).

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Feel free to reopen and elaborate should you want further discussion.
