### ISSUE TITLE
Omeka\Job\IndexFulltextSearch stucks after upgrading to 2.0.2

### ISSUE THREAD

**Issue by pprw** [omeka/omeka-s#1481]
I upgraded few Omeka S to 2.0.2 version. Each time, there is a job `Omeka\Job\IndexFulltextSearch` with no owner which does not finish (stay in starting stage). Therefore, the search is broken just after the upgrade.

The issue is fixed when you relaunch the indexing in /admin/setting. 

It seems to be a bug.

**Comment by zerocrates** [comment]
Hmm... I've seen a problem with the indexer at upgrade before related to modules, but that leads to a status of Error and a logged error message.

You're saying the issue you see is that the job stays at Starting status and there's no log?

**Comment by pprw** [comment]
Yes I have no log and the job stays in starting status.

**Comment by fukuchi** [comment]
Hi,
I installed Omeka S 2.0.2  (not upgraded from the lesser versions) and the same problem happens to me. Here's a job detail from the dashboard:

> Status
> Starting
> Started
> January 22, 2020 4:26:19pm
> Ended
> [not ended]
> Class
> Omeka\Job\IndexFulltextSearch
> Owner
> kentaro@fukuchi.org
> Args
> [no args]
> Log
> [no log]
> Log (database)
> [no log]

**Comment by fukuchi** [comment]
Update: this worked for me.
https://forum.omeka.org/t/omeka-s-2-0-0-search-disabled/9256

**Comment by zerocrates** [comment]
So, on this one:

We didn't reproduce pprw's issue where it's stuck on Starting at upgrade time but works when you hit the button later. fukuchi's looks like it was just a standard case of the server not being set up to run background jobs at all, with the expected solution of switching to "Synchronous" job running.

Obviously the impact of this is pretty blunted since it's only relevant for upgrades from pre-2.0 versions of Omeka S, so I doubt we'll really get more info or interest on this one.
