### ISSUE TITLE
Zend 3 is dead : final roadmap for Omeka 3 ?

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1494]
Zend framework closed on the 31th December 2019. It's now a community driven project with a new name : [Laminas](https://getlaminas.org). 
The upgrade is not complicate to do, there are [migration tools](https://getlaminas.org/blog/2019-12-31-out-with-the-old-in-with-the-new.html) to change the names of the classes, but it will break many modules, that should do the same. So do you plan to do a new release, like for Doctrine? If so, it may be a good opportunity to fix some old issues and to add some important improvements.

**Comment by m-art-in** [comment]
Is there a list of modules which are negative effected?

**Comment by zerocrates** [comment]
There's no list currently, because there are no changes yet. As Daniel says, what's happening is that Zend Framework is changing its name, and because of that they're changing the names of all the Zend classes: so that affects Composer declarations (not a big deal for Omeka S since most modules are not using Composer and those that are mostly do not require Zend components), configuration (likely to affect several modules), and the code itself (changing what classes are extended from and so on).

The migration tools apparently include components to intercept and update both Composer specifications and module configuration that reference old Zend class names, and include aliasing from old names to new ones, so it's possible the change will be fairly seamless, but we haven't looked closely at the issue yet.

**Comment by elazar** [comment]
From what I can see, packages were moved over to Laminas and all class references use the Laminas namespace in #1508, though some have been aliased to names that include a Zend prefix, presumably for the sake of not having to update them everywhere else in code.

Is this issue remaining open to remove the aforementioned aliases, or for some other reason? Or was the work done and the issue was just never closed afterwards?

**Comment by zerocrates** [comment]
The actual changes related to the migration to Laminas live outside this issue, and yes they've basically been completed for the core of S in the develop branch.

This issue, to my reading, was always more about the idea that a migration to Laminas implied a "version 3" release and therefore an opportunity to make other fixes and improvements that are backwards-incompatible. That is the situation at play here; the release including the Laminas updates will be version 3.0.0.

But, this issue on its own doesn't really stand for any specific changes so I'm fine with closing it.
