### ISSUE TITLE
Zendframework and .gitignore

### ISSUE THREAD

**Issue by cscottjames** [omeka/omeka-s#1499]
Very minor suggestion. When upgrading to v.2.0.2, I used Git to manage development, staging, and production instances of Omeka S. This gave me a little bit of grief as the zendframework was in development, but not when I pushed my update to staging. I got around this by removing /vendor/ from my .gitignore. I suggest doing the same, or at least adding a new line with something like "!/vendor/zendframework/".

**Comment by zerocrates** [comment]
All of vendor is ignored because we don't keep it under version control: you should use Composer to manage the vendor folder. We're pretty unlikely to make any changes to that.

If you're using version control on your own to track a particular installation and everything in it, I suppose that would make sense, but it doesn't really work as something to be committed to the project itself.
