### ISSUE TITLE
Feedback on site-item assignment, cross-site search

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1532]
This issue is intended to provide kind of a centralized area for questions/answers/feedback on the site-items changes pending for version 3.

Currently this is the branch site-items.

For reference, the changes here touch:

- the Resources page of a site's item panel: this is an area to make one-time, bulk/batch changes to the assigned items for a site
- a new Sites tab when adding/editing items
- new interface on the "top" public page for searching across sites

**Comment by mebrett** [comment]
One bug which I have found - I have "assign new items" checked for a site. I added an item to the installation as a different user (editor level) and it was not added to the site.

**Comment by jimsafley** [comment]
> there needs to be the same kind of expandable explainer about what "assign new items" does on the Add Site page as there is on the site resources page.

Before we add anything to the "Sites" section, I should note that we're not committed to the text or structure of the site's "Resources" page, so let's focus on that page for now.

For one, maybe we could change "Assign new items" to something like "Auto-assign new items" and the explainer text could be, "Select this to automatically assign new items to this site. Note that item owners may unassign their items from this site at any time." A small change, but maybe a bit clearer. What do you think? Is there other text on the page than could be clearer?

> If selecting an action is required, there needs to be an indication.

Selecting an "Assignment action" is completely optional, but we should make it clear to users who've just created a new site that they should assign items before they start building pages. We could include a "Configure your resources here" link in the success message after creating a site, if it's that important.

This probably is where we need to discuss the general structure of the "Resources" page. The page serves two functions: the "Assign new items" setting and the "Assign these items" process. Is the current structure good enough? Should we change the text or design for better user experience? I'm open to ideas.

> when you submit the form for the first time, it just says there are 0 items and there's no indication that you might need to reload the page

Yes, it's a good idea to tell the user to refresh the page. I'll work on it..

> Site resources do not update if you update the contents of an item set. Is this expected behavior? Would you have to run a new action to update the resources for a site every time you added something to an item set, if that's what you were using?

Yes, this is expected behavior, at least for now. I believe we discussed a possible feature of tying an item set to a site so that all items currently in and newly added to the item set are automatically assigned to the site. I'm not sure where we fell on a decision here.

> Is there a way to add a search for "owned by" so that people could add everything they have created?

This is a good idea. I'll work on it.

**Comment by jimsafley** [comment]
For those who just want to see what the site's "Resources" page looks like:

![Resources · Sites · Omeka S3](https://user-images.githubusercontent.com/141955/79280922-a3aa1300-7e7f-11ea-8052-8fc7d827de9d.png)

And here's the options for the "Assignment action" select:

![Resources · Sites · Omeka S3_2](https://user-images.githubusercontent.com/141955/79280986-d3591b00-7e7f-11ea-89de-d2da2c8243a4.png)

**Comment by jimsafley** [comment]
I added a "Search by owner" option to the form. An advantageous side effect is that it also adds it to every advanced search form in the admin interface. I'm not sure why we didn't have it before now.

**Comment by zerocrates** [comment]
To all: development on this is now taking place on the develop branch, so everyone should be using at looking at that, and no longer site-items

**Comment by kimisgold** [comment]
1)  If you're using the search form, do you need to have an assignment action selected? If so, this is something to consider for the UX treatment: how to indicate a required field for only a section of the page.

2) How do you clear a previously saved search? The best I figure for the moment is to click the remove button on a search row and check the "Save this search" option again.

3) One of the confusing things about "Save this search" is that having the saved search automatically populated in the form implies that the form's state reflects the currently assigned items. I would prefer having saved queries in a selectable list that I can pick from and apply to the form. I can draft a prototype if this sounds appealing to anyone else.

4) I would really prefer the search preview not take the user away from this page, but the current solution is definitely simplest. This problem could be saved as an enhancement for later.

**Comment by jimsafley** [comment]
If you haven't already, please read [this comment](https://github.com/omeka/omeka-s/issues/1532#issuecomment-613181057).

> 1. If you're using the search form, do you need to have an assignment action selected?

There are two ways that the search form comes into play: one is to perform an assignment action using the search results, and the other is to save a search query - both are optional, but the user can do both simultaneously. (To be clear, nothing on the "Resources" form is required.)

> 2. How do you clear a previously saved search?

The only way to clear a saved search is to revert the form to its original state by hand and save that search. Other pages that display the advanced search form have a "Reset" button that clears the form, but this doesn't have that feature.

> 3. One of the confusing things about "Save this search" is that having the saved search automatically populated in the form implies that the form's state reflects the currently assigned items.

The saved search does not necessarily reflect the currently assigned items. The feature is simply a convenient way to store _one_ commonly used query. There is no list to choose from because there is only one saved search at a time. I can see how a list of labeled saved searches could be helpful here, but that would require a change to the data model, which is not out of the question.

**Comment by kimisgold** [comment]
Re: 1. I read that comment and understood the select was not required for
the whole form, but i was still unclear if it was required for using the
search results specifically.

**Comment by jimsafley** [comment]
Sorry I was unclear. When a user selects an "Assignment action," the assignment process will always use the "current" state of the search form. Whether the current state is the "saved" state is irrelevant.

**Comment by jimsafley** [comment]
Perhaps it's helpful to know that the "Save this search" option is an inessential part of the "Resources" form. We could completely remove it and everything would work normally. It's there _only_ as a convenience so the user doesn't have to redo a commonly used query every time.

**Comment by zerocrates** [comment]
I think the confusion here is that you _can_ use the search without choosing any of the assignment actions: if you're just editing the saved search for later, _but_ since that's a separate control it allows for a kind of "null" action, which is in fact the default.

I imagine Kim's concern (stop me if I'm wrong) is that the design of the form allows you to change all the search inputs and so on, but have selected neither an attachment action nor the "save" checkbox, with the result that all your changes to the search form didn't do anything and are "lost" if you submit the form.

**Comment by kimisgold** [comment]
Yes, exactly what John said.

**Comment by kimisgold** [comment]
Jim and I worked on a UX treatment on the `site-items-ux` branch. Here are the main changes:

* The "auto-assign items" option has moved to "Site Info" as it's one of the settings the user gets upon site creation. It also focuses the site items tab.
  * The site items tab now includes a notification to alert the user if they are currently auto-assigning items upon creation. This is a link that takes them to the "Site Info" form where they can change the setting.
* Within "Resources > Items", the user sees only the "Manage current items" field on load. 
  * All the actions have been restructured as radio buttons so that all options are immediately presented to the user.
  * The advanced search form only appears if the user selects actions that use it: "add", "replace", and "remove". 
  * The "Save this search" checkbox has been re-styled, and it now only appears with the advanced search form for applicable actions.

**Comment by mebrett** [comment]
Language tweak - change the language from "save this search" to "keep this search" just to clearly communicate that the search is not saved forever, but is instead just short-term sticky.

**Comment by zerocrates** [comment]
on the new ux branch:
- tweaks to action wording
- "save this search" -> keep
- explore non-button styling of save/preview
- reduce linked text from "auto assign" warning
- move/shrink add buttons within search

**Comment by mebrett** [comment]
I like the new arrangements. There's still the issue that after you take an action (whether it's replacing, removing, adding, or deleting) the item count doesn't update unless you refresh the page, even though the page reloads without the form. I *know* that's going to stress out some of our users.

**Comment by zerocrates** [comment]
The only way for that count to update immediately would be to do the updating synchronously instead of in a job.

That might actually be feasible on the scale of a single site though...

**Comment by kimisgold** [comment]
I think we discussed some kind of language indicating that a refresh is required for the page to reflect updates. Was that something else?
