### ISSUE TITLE
Improve default cross-site search styling

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1559]
My main concrete comment is about the "list" styling of the sub-results listing which sites each item appears in, and that we probably want to move that to a more compact form that uses some of the copious horizontal space available on that interface.

**Comment by kimisgold** [comment]
There's a new pass at styling the cross-site search up on the [`fulltext-search-styled`](https://github.com/omeka/omeka-s/tree/fulltext-search-styled) branch ready for a look.
The main changes:

* Added the public root url to the main heading so that you can get back to the main search and site listings.
* The query has been added to the headings of the site page results and item results for consistency and in case the query gets modified in the search form.
* Moved the "Sites" list heading closer to site titles because it was a little disconnected from the site listings with the inclusion of the search form.
* Added "Search site pages" and "Search items" as submit button labels for the views that search only those resources.

**Comment by kimisgold** [comment]
Well I mistakenly branched off develop, so I've applied pretty much all of the above to the `[site-cross-site-search](https://github.com/omeka/omeka-s/tree/site-cross-site-search)` branch. I left off adding the public root url to the main heading because I'm the least confident about that change.
