### ISSUE TITLE
Apply "search resources" setting to cross-site search in sites

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1566]
The same setting that controls the sitewide search resource should control the cross-site ones.

A previous implementation of this was briefly in but wasn't accounting for item sets (which were added to the cross-site search later).

**Comment by jimsafley** [comment]
What would be the disadvantage of merely applying the current `search_resource_names` setting to the cross-site results? To me it seems too nuanced a difference to justify the additional setting.

On the other hand, it seems more likely admins will want a global setting that controls which resources are searched on the top-level pages, since no such control exists right now.

**Comment by zerocrates** [comment]
> applying the current search_resource_names setting to the cross-site results

That's what this issue suggests
