### ISSUE TITLE
How to access the api endpoint in admin?

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1613]
Some dynamic features (like [Item copy](https://omeka.org/s/modules/ItemCopy/)) requires access to the api endpoint in admin board, but this one is only available when a api token is set, so it's complex to use for normal users. 

Is there a way to use the standard authentification in the api too? It will allow to improve the admin board simpler. Of course, it's easy to create a quick module to override or to proxify the endpoint, so the main question is it an interesting feature or not for the core?

**Comment by Daniel-KM** [comment]
Such a feature can be used in the right sidebar when searching in a linked resources in resource form.

**Comment by zerocrates** [comment]
My default feeling is that a module that just proxies to the API manager would be fine, but I could be persuaded otherwise

**Comment by Daniel-KM** [comment]
There are two ways to do it: use a password authenticator as a fallback of the token authenticator, or a specific proxy. The two ways can be done in a module because many things can be overridden, but the point is that if multiple modules need this requirement, will they all create a proxy or override the authenticator? I'm going to include a proxy in my module for now.

**Comment by Daniel-KM** [comment]
Ok, I'm going to include a proxy in my module for now. But the point is that if multiple modules need this requirement, will they all create a proxy or override the authenticator?

**Comment by zerocrates** [comment]
Just pulling in my comments from the associated PR:

My view here is that to do this it would need to be a separate endpoint, and it has to deal with the security issues around cookie-based access. If it's going to be full access then CSRF tokens or something similar will be needed to protect against a CSRF-type vulnerability that uses the user's active session cookie. Another possibility might be having an endpoint that does use the cookie but is restricted to only viewing, so it can't do update/delete/etc.

I think just in terms of it standing for a more "wide open" strategy, I'll close the issue here as well, but am still open to something along the lines described above.

**Comment by zerocrates** [comment]
The merge of #1979 included the "read-only endpoint" version of this.
