### ISSUE TITLE
Match sidebar icons for resources to icons used elsewhere

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#162]
There's been a pattern established on the edit and show pages for resources that differs from the all-same "stack of blocks" icons currently being used on the sidebar nav.

**Comment by kimisgold** [comment]
I imagine there's going to be dissatisfaction with the 'Resource Templates' icon, but I wanted to put in something so that it wouldn't be the only duplicate icon in the side navigation. I'm definitely open to alternatives. (See: <a href="http://fortawesome.github.io/Font-Awesome/icons/#web-application">Font Awesome library</a>)
