### ISSUE TITLE
HTTP/2 issues on administrative backend

### ISSUE THREAD

**Issue by mackensen** [omeka/omeka-s#1660]
We've deployed Omeka S v2.1.2 on AWS Fargate with an elastic load balancer. One issue we encountered is that the navigation editing interface performs poorly when the load balancer has HTTP/2 enabled. Note that it's talking HTTP/2 to the client; communication between the load balancer and the container running Omeka is HTTP/1.1.

What we saw was requests proceeding slowly, with many timing out. On a site with 50-70 navigational items, the page never fully loaded, about half the requests failed, and my authenticated session was logged out part way through. Disabling HTTP/2 on the load balancer cleaned up all these issues immediately.

I can generate logs or HAR files if necessary to better demonstrate the issue, but I thought I'd mention in case others have seen this or have a better idea of what the issue was.

**Comment by zerocrates** [comment]
Huh... I can't imagine that HTTP/2 should make any difference to us, particularly since we're only seeing 1.1 requests... I don't have any immediate ideas on what if anything could be causing this on our end.

We've deployed S instances on servers with direct HTTP/2 support (with Apache mod_http2) and not encountered any issues. I wonder if this issue is unique to AWS and/or Fargate, or something else.

**Comment by mackensen** [comment]
Yeah, it was genuinely strange. It's entirely possible that there's some other underlying issue. Another possible factor is that the environment is highly-available, but switching between sticky and non-sticky sessions didn't appear to have any effect.

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Feel free to reopen and elaborate should you want further discussion.
