### ISSUE TITLE
Linked resources Title values can't be translated

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka/omeka-s#1665]
Hello,

I'm working on a theme which implements localization based on property values 'lang' tags.

The only thing I'm struggling to translate without modifying the core is the following: in `common/resource-values.phtml` linked resources are rendered using `$value->asHtml()` which in turn calls `AbstractResourceEntityRepresentation:linkPretty()`.

`linkPretty()` assumes we want the dcterms:title term as a title. This may differ because : 
* there is a per site setting to set up a custom Title term
* there may be multiple values in the dcterms:title property and we want to chose one of them

I'm  addressing the second use case where we would like to chose one of the dcterms:title values, and more specifically here based on 'lang'.

If we have a country as a resource that has a title in multiple languages, e.g. dcterms:title = "Germany" (en-US) / "Deutschland" (de) / Allemagne (fr), and we want this country as a linked resource for a location property value, we won't be able to display the title in the correct language.

I'm a bit confused on how to implement this but if this makes sense and is of interest to the project, I'd love to submit a contribution.

**Comment by ManOnDaMoon** [comment]
As a live example, you can check this page: https://collection.manondamoon.com/s/en/item/5

You can switch language using the 🇬🇧 and 🇫🇷 links in the top bar.

You'll see it is has Germany as a property value, but with the link being in french "Allemagne". Switching languages back and forth, you'll see that everything gets translated _except_ for the country name that can't be changed to "Germany" although if you navigate to the resource it has "Germany" as a title value.

**Comment by matthewjmckinley** [comment]
Hi! `linkPretty()` is used pretty extensively throughout the core code, so I think we want to avoid modifying it for a more specific need unless there's truly no other option.

Since you mention `common/resource-values.phtml`, which is the default view script for `displayValues()`, am I correct in assuming you are have retained this function in your custom theme for the resource view page? If so, `displayValues()` will accept a custom view script or view model as a parameter:
https://github.com/omeka/omeka-s/blob/692dbab768b67f4e2ff67aa630ac99c68d90375f/application/src/Api/Representation/AbstractResourceEntityRepresentation.php#L454

You could potentially write your own view model (or one based off `common/resource-values.phtml`) that would select the proper title value based off the lang attribute, instead of just calling `asHtml()` by default.

**Comment by ManOnDaMoon** [comment]
Hello Matthew and thanks for your insight.

My theme is based on foundation-s and you can see in this PR ´: https://github.com/omeka-s-themes/foundation-s/pull/25/files that changes are extensive but in the same time quite not so. I was refraining to further modify resource-values.phtml because this means handling a lot of data types but this may be overthinking. I’ll have a look at what I can achieve there.

**Comment by ManOnDaMoon** [comment]
Well [that wasn't as complex as I expected](https://github.com/omeka-s-themes/foundation-s/pull/25/files#diff-568970e1d8dc2772f31f439d49b2d19e5451e43f434b61ea028c0b6c757bad5c)
