### ISSUE TITLE
Increase html editor vertical length 

### ISSUE THREAD

**Issue by pprw** [omeka/omeka-s#1677]
When editing/creating html media, the editor takes only half the vertical space for (seems to me) no specific reason. There is a lot of space unused (especially when editing an already created html media).

You have to increase it each time by hand if you have more than few lines html content.

I propose to use all the vertical space available.

Now (editing media):

![image](https://user-images.githubusercontent.com/5262986/103996072-9bc29980-5199-11eb-9a8d-fad4554d692f.png)

Proposal:
![image](https://user-images.githubusercontent.com/5262986/103996137-b432b400-5199-11eb-8602-ae2b48e87839.png)

Now (creating media):

![image](https://user-images.githubusercontent.com/5262986/103995646-0de6ae80-5199-11eb-9ea7-5b3bea0c6d27.png)

proposal:

![image](https://user-images.githubusercontent.com/5262986/103995740-28b92300-5199-11eb-931b-ea659812cb02.png)

**Comment by zerocrates** [comment]
I don't think we want to do any big changes to the size of the box on the _item_ page: just because items can have many media entries so having a really big HTML box might make that annoying to deal with.

We do know that it's the only thing on its tab on the media edit so I don't think expanding it is a problem there, though.
