### ISSUE TITLE
Workshop Interface Language for Query Builder

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1696]
Here's a spot for thinking through the language for the buttons in the query builder for "edit" and "edit query string."

This will be in addition to making the Clear button appear and disappear when there is a query present.

Related to #1693 and #1639

**Comment by kimisgold** [comment]
Alternatives to "Edit"
* "Configure"
* "Build"
* "Open query builder"

Alternatives to "Edit query string"
* "Manual edit"
* "Advanced edit"

These are some of my initial suggestions as well as some brought up in sprint review. Open to other ideas and feedback, particularly from @sharonmleon, @georgiawebgurl, @mebrett

**Comment by georgiawebgurl** [comment]
One more thought - For some communities/folks, Edit implies that there is already something there. So, I create (or build or configure) and then edit. At least from a library/metadata world Edit is most often an action taken after a create/customize/build/configure process. 

Configure or Build seem like they could cover either the creation or editing process.... but I am fine with any of the choices discussed. My original thoughts on terminology were that Query was a little too technical for a general user, while Search is understandable to most users. So, Search/Query were really the largest terminology issues from my viewpoint. :-)

I do think like Advanced - maybe even something like Simple Build, Advanced Build? 
Or Build and Advance Edit Search String ? I think it's ok if the Advanced is a little more well... advanced terminology. 

I am fine with Restore and Clear. Preview, Reset, and Apply are all fine, too.

**Comment by jimsafley** [comment]
The two things under discussion are "Search vs. Query" and "Edit vs. Configure/Build."

I prefer Query over Search because, while the user is performing a search, they are actually building and saving a query. Also, we are already using Query in more areas than Search. The only area that used Search was site resources. I changed it to Query for consistency.

I understand your point about the distinction between edit and create, but the user is never really creating a query because an empty query is essentially a query that means "all resources."

As for Edit vs Configure/Build, let's discuss this in terms of buttons. Right now they are Edit / Advanced edit. I like the consistency of that, which is primarily why I prefer it over the alternatives. Let's look at some alternatives:

- Configure / Advanced configure
- Build / Advanced build
- Configure query / Advanced edit
- Build query / Advanced edit

I'm just not getting the same impact as from Edit / Advanced edit. I'm also not sure if many people associate "build" with a query.

**Comment by kimisgold** [comment]
We do currently use "query" elsewhere in the interface, but typically with little context and in areas we're hoping to make friendlier to users. I'm wondering if using "Search query" as the field label might strike a balance in specificity and giving our users better context.

I'm fine with shipping "Edit/Advanced Edit" for the moment if we need more time to improve the language. In the meantime, my main pain point is that "Edit" feels like an awkward description for the sidebar. I would like something that better signals a GUI. Right now, it feels generic and defined by its contrast to the "Advanced Edit".

> ...an empty query is essentially a query that means "all resources."

This is one of the things I think we could be better at conveying to the user. Instead of "Edit below", I think we could have language to this effect: telling the user that the query is currently retrieving all resources.

**Comment by jimsafley** [comment]
The query builder was merged in #1707. As of now we're using "Search query" for the labels and "Edit / Advanced edit" for the buttons. Keeping this issue open until we settle on terminology.

**Comment by georgiawebgurl** [comment]
I had a thought on this issue yesterday afternoon. 
How about Customize for Edit/Advanced Edit ?  Or maybe Configure / Customize? 

I've been thinking about workflow terms I've seen in ILS (Integrated library systems AKA library catalogs) as well as in other web interfaces. 

I'm ok with Edit/Advanced edit as I think that makes some sense to users. Query still feels a little tech lingo-eseque. I understand the distinction between doing a search and building a search, but I wonder how many of our users would make that distinction. Certainly, the ones with some tech building skills would.
