### ISSUE TITLE
Why is there a "Media" tab in the item set add/edit page?

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#170]
Media can only be assigned to an item.

**Comment by patrickmj** [comment]
I can see the possibility that not having media for item sets will lead us back quickly to the 2.x complaint of collections not having their own images.

**Comment by patrickmj** [comment]
looks like me and Ken were on this in close succession. I do want to address the media problem. it's been a common thing in the dev list, and I think we should keep media attached to everything we can if at all possible

**Comment by zerocrates** [comment]
I don't remember it ever being even planned to have media attached to sets.

We're providing the "representative" thumbnail as in classic and I think
that's sufficient

**Comment by patrickmj** [comment]
can't say I agree. people think of an image for something the way they think if a title, it's distinct from the content. generally, for example, the title of an anthology is not the title of one one the included articles. similarly, the image for a set shouldn't be picked from the items in that set

**Comment by patrickmj** [comment]
Want to ping this while I'm in the item set form, to see if there are additional thoughts or responses. Again, I don't think representative image is sufficient. For example, a narrative description of an Item Set might not be best forced into dcterms:description -- it would make more sense as HTML. Or, to other media, a video introduction to an ItemSet seems perfectly reasonable. 

If it isn't a strain on the data model, I don't see a reason to restrict people, especially since we've done such work to make other Resources have media.

If not this cycle, I think we should bring it up at the next planning for more discussion.

**Comment by patrickmj** [comment]
Just another piece of evidence about this issue, as it related to DSpace that I hadn't noticed before.

DSpace Collections have a `logo` data field. I haven't seen it used much in the imports I've been doing. But importing a DSpace collection would correspond to an S Item Set, and it'd be nice to not lose that data, when present, if people want S to be a front-end on DSpace

**Comment by jimsafley** [comment]
The media tab is no longer there and I think #550 satisfies @patrickmj's concerns above. Can we close this?

**Comment by sharonmleon** [comment]
No one responded here. I'm closing it.
