### ISSUE TITLE
In site pages, anonymous users can see public items without media but not public items with a private media

### ISSUE THREAD

**Issue by jajm** [omeka/omeka-s#1708]
To reproduce:
1. Create a public item (A) without any media
2. Create another public item (B) with one private media
3. Create a site page with a block 'Item showcase'
4. Add items A and B to the item showcase
5. Logout and go see the page, you should see only item A

I believe that items without any visible media should be treated the same as items without any media.

**Comment by zerocrates** [comment]
I haven't looked closely into this but I imagine it's because the attachment with a private media has that media selected: the logic for dropping an attachment from public view is if either the selected item or the selected media is private.

We could change this to allow it in the scenario you're describing... but my sense is that many people wouldn't want to show the attachment at all if the media won't be there.

**Comment by jajm** [comment]
Both scenario make sense I guess... But it seems strange that adding a media to an item will hide it from public view. And removing the media will make it visible again.

Items "browse" page behaves differently, as it show public items even if all their media are private

Also, consider the following scenario:
1. Create a public item without media
2. Attach it to a page block (the item is now visible)
3. Add a private media to the item (the item is still visible as the media was not selected in the page block)
4. Edit the page, open the attachment options, click on "Apply changes" without changing anything, save the page
5. Now the item is hidden and there's no way to get back to the state before the page modification

If it's not possible to decide which one of the 2 options are the best. What do you think about letting the user decide, with an option "Hide attachment if media cannot be shown" for each attachment (or for the whole block) ?

**Comment by jimsafley** [comment]
Further discussion is ongoing in #1846
