### ISSUE TITLE
Reconsider PATCH behaviour regarding RDF properties update

### ISSUE THREAD

**Issue by pablovp86** [omeka/omeka-s#1719]
As [stated into the API Docs](https://omeka.org/s/docs/developer/api/rest_api/#partial-update-patch):

>  Note that specifying any values for RDF properties (the "values" for items, item sets, and media) will be treated as an "update" to the values generally (meaning that specifying any value for any RDF property **will mean the removal of all other values that aren't passed**). In other words, the values are treated as if they're one big "key" for the purposes of patching.

The behavior of the PATCH verb regarding RDF properties is quite non intuitive, which causes [problems for unaware API users](https://forum.omeka.org/t/help-with-rest-api-patch/11611/3).

API users would expect to send the updated data only, the set of changes, [as estates the HTTP PATCH RFC](https://tools.ietf.org/html/rfc5789#section-2). This will save them from making a GET request, only to fetch all the RDF fields to send on the PATCH request, for example.

**Comment by zerocrates** [comment]
Do you have an opinion on the specific change to PATCH you're looking for here? Using something like JSON Patch as brought up in the thread you linked to, or something else?

**Comment by pablovp86** [comment]
@zerocrates 

I think the behavior, [expressed on the docs](https://omeka.org/s/docs/developer/api/rest_api/#partial-update-patch), could be reconsidered:

> Note that specifying any values for RDF properties (the "values" for items, item sets, and media) will be treated as an "update" to the values generally (meaning that specifying any value for any RDF property will mean the removal of all other values that aren't passed). In other words, the values are treated as if they're one big "key" for the purposes of patching.

This means that to ensure that no properties are deleted, all properties must be sent, even the unchanged ones.

For example, imagine an item with two RDF properties `dcterms:title` and `dcterms:description`.  Today, to change only `dcterms:description`, the PATCH request must include `dcterms:title` property. If `dcterms:title` is not present, it will be removed from the item, an unwanted behavior.

I propose that only the RDF properties present on the PATCH request must be considered. On the last example, if a request is sent with this body fragment: 

(...)
```
"dcterms:title": [{
		"type": "literal",
		"property_id": 1,
		"property_label": "Title",
		"is_public": true,
		"@value": "Another Value"
	}],
```
(...)

Then only `dcterms:title` should be changed.

**Comment by raboof** [comment]
> Instead, only the RDF properties present on the PATCH request must be considered.

I would also expect/prefer this behaviour.

> We don't currently plan on addressing this issue.

That's fair enough. However, would you be open to a contribution changing the behavior like this?

> The only way we see this working is with JSON Patch because it would not require backwards incompatible changes

It is true that strictly speaking changing the PATCH behavior to the one @pablovp86 describes is backwards incompatible. It is backwards incompatible in a somewhat narrow set of cases, though: only clients that use this method to delete RDF fields would be impacted. Clients that perform updates without dropping fields would see no change in behavior (since they are repeating all fields with their current values anyway). Any clients that relied on the old behavior can likely fairly easily switch to using PUT instead. For clients failing to make this change before their Omeka-S instance is updated the impact is limited: fields that should have been deleted would be incorrectly retained, but no data would be lost.

Are there any known clients that use PATCH to delete fields?
