### ISSUE TITLE
Constrain site asset thumbnail sizes

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1745]
With site lists the size of the thumbnails should be constrained for consistency. In the default site context, they should be consistent.

In the themed site context, the thumbnails should be governed by the parameters that control the item thumbnails.

**Comment by kimisgold** [comment]
I've updated styles in the default site context to have constrained thumbnail widths. They're ready to be pulled for testing. I can create a testing issue or we can provide feedback here, whichever makes more sense.

For the the themed site contexts, let's create issues in the respective repos for better tracking.

**Comment by sharonmleon** [comment]
I've got a site listed with no media or description and it's pushing the second site info to the right.

![Screenshot 2021-07-27 at 11-55-44 Sites · SML Omeka S Test](https://user-images.githubusercontent.com/741480/127186817-e5bb6ae4-26d1-44c0-be17-a7d773e788da.png)

**Comment by kimisgold** [comment]
Sorry, that's as intended. The new styles have the sites listed in a two column layout, each site taking up 50% of the width. The descriptions become long and unwieldy otherwise. It looks awkward here, but I would make the argument that projevts utilizing assets and thumbnails for site should use them consistently across their sites if they want to use this view. 

Here is an example of the site list view with only text

![image](https://user-images.githubusercontent.com/606764/127188740-2343e299-8b0c-4495-9e98-79845bae96e4.png)

**Comment by sharonmleon** [comment]
Ahh... I get it. I just have an ugly set up :)

**Comment by sharonmleon** [comment]
Okay. Looks good with the new set up. 

Remaining question: Should the small thumbnail be enlarged to fit a standard width?

**Comment by kimisgold** [comment]
Good question. I'm tempted to say no since I dislike stretching smaller images larger. Right now all those images share a maximum possible width, so they're at least consistent in that respect.

**Comment by sharonmleon** [comment]
Sounds good. 

With that, I think that things look good on the main site list. On to the themes.....
