### ISSUE TITLE
Sites: Ordering of page blocks in sidebar

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1751]
In the process of running a testing install I have 15 page blocks at my disposal. They are not ordered in a way that suggests any logic, and as a result things are hard to find.

Some options: 
- order them alphabetically
- create divisions for core blocks and module blocks
-  others?
![Screenshot 2021-07-27 at 20-48-44 Edit · Welcome · Pages · SML Omeka S Test](https://user-images.githubusercontent.com/741480/127503553-282d3fc4-4577-4806-bda7-1226279cf768.png)

**Comment by kimisgold** [comment]
I like both these ideas. For alphabetical, would this work across translations?

**Comment by jimsafley** [comment]
We currently have the ability to modify the order of services using the `sorted_names` configuration option. Right now it's only being used by `block_layouts` to put the HTML block at the top. We could alphabetize the core blocks using `sorted_names`, but that would do nothing about blocks added by modules, which would just be listed underneath in no particular order. Otherwise, I'm not sure how we'd differentiate between blocks added by the core and blocks added by modules.

We could change this behavior by alphabetizing the blocks (or all services for that matter) during runtime using something like this where we're listing the blocks:

```php
$registeredNames = $this->registeredNames;
usort($registeredNames, function ($a, $b) {
    return strcmp(
        $this->get($a)->getLabel(),
        $this->get($b)->getLabel()
    );
});
```
