### ISSUE TITLE
Error in list-of-pages-block-layout.js when "Add Attachmant" Button from Item showcase block is clicked

### ISSUE THREAD

**Issue by grandgeorg** [omeka/omeka-s#1817]
There is an JS error in `list-of-pages-block-layout.js` when the "Add Attachmant" button from "Item showcase" block is clicked.

As `$('#content').on('o:sidebar-content-loaded', '.sidebar', function(e){ ... });` gets triggered but `currentTree` is `undfined` the script crashes with:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'get_json')
```
So for a quickfix one should check if `currentTree` is undefined e.g.:

```js
            // Remove already selected pages by comparing slugs
            if (typeof currentTree !== 'undefined') {
                $(currentTree.get_json('#', { 'flat': true })).each(function(index, value) {
                    $(pageLinks).each(function() {
                        if ($(this).attr('data-id') == value['data']['data']['id']) {
                            $(this).hide();
                        };
                    });
                });
            }
```

https://github.com/omeka/omeka-s/blob/a5edf2dac848e62b6926727558bbba0a9e7a99c4/application/asset/js/list-of-pages-block-layout.js#L89

**Comment by matthewjmckinley** [comment]
Thanks for finding this! There is actually a pull request in to streamline the ListOfPages sidebar operation which also happens to fix this issue, by attaching to the ListOfPages-specific `site-page-add` button instead of the more general `o:sidebar-content-loaded` event. 

https://github.com/omeka/omeka-s/blob/515241b915da3f627f9d8f4c369ff73d5cb8d2ad/application/asset/js/list-of-pages-block-layout.js#L75

This fix should be in soon. I've confirmed the fix works locally, but if the issue persists after the PR is integrated we can re-open this issue.
