### ISSUE TITLE
Resource Creation -- OS Resouce Linking Sidebar: Print OS ID next to title in quick add list or in the resource preview

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1821]
Printing the OS ID in more places can really help with disambiguation of Omeka S resources that share the same title. This is especially true when selecting an item or item set as a value in the process of creating a new item. 

See images below:
![image](https://user-images.githubusercontent.com/741480/155228378-98aee8af-b17c-473b-9394-2d06ce5eb5d3.png)
![image (1)](https://user-images.githubusercontent.com/741480/155228384-a350f2be-4da8-48f0-afbe-6ac746924645.png)

**Comment by zerocrates** [comment]
Certainly we should align the "details" sidebar information to include it as the regular show sidebar does (your second shot).

The listing... i think it can work there also but requires a little more finesse (and attention to the many other places we have similar lists).

**Comment by sharonmleon** [comment]
I think either would be good. 

For the list, I was thinking that the inclusion of a parenthetical in-line with the title would do it, but that might make a wrap situation that would shift things a lot.

**Comment by zerocrates** [comment]
You'd probably want it to be a kind of "column" to avoid spoiling the straight left-edge alignment of the titles, though since it's numbers which are usually pretty fixed-width you might get away not really worrying about it so much. Or they could be directly after the titles, or right-aligned in the usually-empty space there... many options.

Though having them in the listing here probably brings up the question of the main browse listings... it's definitely just not as straightforward.
