### ISSUE TITLE
Test navigation link management behavior

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1826]
On the `develop` branch, test the following behaviors in the "List of Pages" block within the page editor:

* Add links to the block from the sidebar.
* In the sidebar, use the search to filter pages. Check that pages that have already been added to the block do not appear in the filtered results.
* Private pages appear as options to add to the block.

Please also check that the above behaviors in the site navigation editor. The two views share a lot of code, and we want to check for any bugs to the site navigation that the list of pages changes may have introduced.

**Comment by zerocrates** [comment]
Just one side bit to make sure to double-check would be that everything's fine when there are _multiple_ "list of pages" blocks on the same page, and moving between editing them.

**Comment by katknow** [comment]
This seemed to work well. Can multiple lists of page blocks that don't interfere with one another, there doesn't seem to be nav conflicts, can add private pages, filter seems to work as described. I don't know if it's relevant because I was unable to replicate it, but I did get this error at one point:

Warning: array_walk() expects parameter 1 to be array, string given in /var/www/html/katknow/OmekaSTesting/application/src/Site/BlockLayout/ListOfPages.php on line 97

**Comment by zerocrates** [comment]
Yeah, that's an interesting error... it means your saved data for the pages set to the block was just a simple string somehow. Not really sure where that would have come from.

**Comment by zerocrates** [comment]
If you can't reproduce it I think we'll file it away as an artifact of having used testing/in-progress blocks so much, at least unless/until we get another report.
