### ISSUE TITLE
Supervisor role cannot import new vocabulary

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#1857]
No "Import new vocabulary" button. They also can't edit or delete. 

If it's up in the air, I would vote to give them importing & editing but not deleting. Or maybe just editing their own vocabularies, not the base ones / ones installed by the global admins. The manual says:

> Search, read, and create privileges for Vocabularies (cannot delete)

which doesn't say anything about editing either.

**Comment by sharonmleon** [comment]
I'd vote for
 - Search and read
 - Import, edit, and delete own
 - Not delete those owned by others

Edit in this context actually does make sense, since it means that you can change the language and label application. And also, reimport/update the vocab. 

There is, of course, a question of whether or not Vocabs actually have owners.

**Comment by zerocrates** [comment]
So yeah just to get the lay of the land here, the actual rules in current usage explicitly deny the import page, and underlying create/update/delete for vocab objects, from the Supervisor role.

Vocabularies do have owners recorded for them.

**Comment by zerocrates** [comment]
Branch vocab-supervisor contains the fix here: it allows supervisors to do the import, and to update/remove only the vocabs they themselves imported.

**Comment by sharonmleon** [comment]
Can confirm that with Supervisor role, I can
- see and use, but not edit existing vocabs
- import new vocab
- edit those I import
- delete those I import
