### ISSUE TITLE
Incorrect linking to referenced items

### ISSUE THREAD

**Issue by m-art-in** [omeka/omeka-s#1868]
I don't know if it's supposed to be a new feature or if it's a bug:

OMEKA VERSION: 3.2.0

The following scenario: I have created two sites in Omeka S: A and B.
Item 1 is assigned to both A and B. Item 2 only on site B, but is referenced from 1. 
When I view item 1 on site A, it links to item 2 even though it does not belong to page A. Actually, the reference link should then point to site B, but item 2 is displayed under site A, even though it is not part of site 1.

In the backend the linking is done as "Omeka Resource", as a workaround I could use a URI linking, but if the item is changed or deleted the URI link does not adapt as nice dynamically as a linking as "Omeka Resource".

I have noticed the same behavior with links to public/private resources. Links are displayed, although the item to be linked is private.

**Comment by zerocrates** [comment]
I think this is all as it's been in all versions.

Items will display across the site boundaries if you manually link over to them; this was done intentionally to allow the links not to be broken in cases like this where an item has a link that crosses outside of the pool of items assigned to the site it's currently being viewed in. To some extent this decision is also a legacy of the prior item pool system which worked based on a "saved search" model, where calculating if a given item was part of a given site was a relatively expensive operation.

3.2 contains an update to add a meta tag to tell search engines not to index these "out of site" pages if they crawl to them, but otherwise makes no changes here.

What would you want to see this do instead? Choosing to link to B specifically is tricky just because items can belong to many sites and we don't really have a concept of a "preferred" site to link to. In the current setup it would be feasible to just hide the linkage, though if we were going to offer behavior like that I think we'd have to make it an option people opt into.

As for private items, those links should not display if you don't have access to view the private item. If you're logged in as an administrator, you'd see them but public anonymous users would not.

**Comment by m-art-in** [comment]
Thank you for your detailed explanations. I also see it as a problem if the item 2 is not only on site B but also on site C / D etc.. Then it is really completely unclear where the link to item 1 should lead to. 

What I would therefore find desirable is your suggestion with opt in very good. 

Or disable the linking and show only the text if the item to be linked is not part of the site. That would be probably the fastest realizable solution.
