### ISSUE TITLE
Testing: New system information

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1877]
We've added three new things to the "System information" page that's linked in the admin footer.

First, there's the "Modules" section that lists every module and version categorized by status. To test this, just verify that the information is correct by comparing it to the Modules browse page.

Second, there's the "Paths" section that lists the "PHP CLI path" and "ImageMagick directory" paths. To test this, you'll need to confirm that both are correct and reflect what is configured in your `config/local.config.php` file under, respectively, `[cli][phpcli_path]` and `[thumbnails][thumbnailer_options][imagemagick_dir]`. You may set a random string for the test, but remember to put it back to its original value after you're finished.

Third, there are two buttons: "Get PHP CLI version" and "Get ImageMagick version". Test these by clicking on them. A text box should appear containing information about the command's version.

**Comment by katknow** [comment]
The modules list and button all seem good to me. The one thing I'm not sure about is the Paths. The file shows this:

<img width="736" alt="Screen Shot 2022-08-09 at 10 55 34 PM" src="https://user-images.githubusercontent.com/84726696/183800903-7d216ba3-4338-42fa-9029-97afe93f548c.png">

Whereas the System Information page says this:

<img width="499" alt="Screen Shot 2022-08-09 at 11 02 04 PM" src="https://user-images.githubusercontent.com/84726696/183801009-fc5ea25d-fec3-4ac5-ad1e-f79c89cfe035.png">

I'm guessing it's okay because when I change it to a random string it does update and when I change it back I get the same results as shown above, but I just don't know enough about it to be sure since it doesn't exactly match. 

Also, this is a bit nit-picky, but I think there might need to be some padding between the results of the "Get PHP CLI version" and the button for "Get ImageMagick version":

<img width="726" alt="Screen Shot 2022-08-09 at 11 03 30 PM" src="https://user-images.githubusercontent.com/84726696/183801197-224a9597-b27d-4ee9-8da3-92bf0f7a5072.png">

**Comment by jimsafley** [comment]
> I'm guessing it's okay because when I change it to a random string it does update and when I change it back I get the same results as shown above, but I just don't know enough about it to be sure since it doesn't exactly match.

When the paths aren't included in the config file, we try our best to get them automatically. This is what you see when the paths are set to null.

> Also, this is a bit nit-picky, but I think there might need to be some padding between the results of the "Get PHP CLI version" and the button for "Get ImageMagick version":

@kimisgold Would you like to take a look at this and make styling changes?
