### ISSUE TITLE
Add thumbnail_display_urls to @reverse

### ISSUE THREAD

**Issue by sinanatra** [omeka/omeka-s#1896]
Would it be possible to add `thumbnail_display_urls` or a way to link to the main media to the `@reverse` key? 
That way it would be possible to parse the content of `@reverse` without querying every single element to fetch the medias.

**Comment by zerocrates** [comment]
One issue here is that `@reverse` is purposely quite minimal in what it retrieves, because it's very feasible for _lots_ of resources to link to a single one. Getting the thumbnail URLs requires us to at least add a join, and if we want to keep it as just a query, add some equivalents to the logic that we use to handle custom thumbnails and so on. I'm not sure this would really work out.
