### ISSUE TITLE
Testing: Users can set default item sets

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1949]
On the develop branch, users can now set which item sets are automatically added to the "Item sets" tab when adding a new item. To test this, go to Users > Edit > User Settings, and under "Default item sets for items" select a few item sets. Save the form. Then add a new item and confirm that the item sets you selected are already chosen in the "Item sets" tab.

**Comment by katknow** [comment]
This does work, but I wonder if it should override a closed item set. I assigned a second user a default item set from my admin account but forgot to go into the item set and open it, which admittedly confused me for a bit. If I am assigning them the item set, I would assume it overrides the lock because it allows some folks to add to it but generally keep it locked since this feature is enabled on a user-by-user basis. But, I can also see where that might be dangerous for a carefully curated item set.

**Comment by jimsafley** [comment]
For the reason you state at the end, a locked item set means it's locked for _all_ uses unless the user has permission to edit the item set.
