### ISSUE TITLE
Message saying there is no media

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#206]
When an item has no media, there should be a message in the "Media" tab of the item add/edit pages.

![omeka s 2](https://cloud.githubusercontent.com/assets/141955/8013527/f212c83a-0b97-11e5-9500-8dc5e6f23d94.png)

**Comment by kalbers** [comment]
I'm happy to tackle this one, but I'm not quite sure where the problem is. Visual is confusing/unclear.

**Comment by jimsafley** [comment]
How about this?

![omeka s](https://cloud.githubusercontent.com/assets/141955/8040271/0c3c1ada-0ddd-11e5-9bad-5951de3d99cb.png)

**Comment by kalbers** [comment]
Clears it up entirely! Thanks!

**Comment by kimisgold** [comment]
Maybe something like the media/browse view if you have no media throughout Omeka.

![no-media](https://cloud.githubusercontent.com/assets/606764/8040947/af7d4020-0de2-11e5-90c3-e8a870568ec2.png)

Instead of "Omeka could not find any media," the item/resource form could say, "This resource has no media. Start adding media using the interface to the right."
