### ISSUE TITLE
Testing: linked resources interface

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#2178]
The [fix-linked-resources-interface](https://github.com/omeka/omeka-s/tree/fix-linked-resources-interface) branch aims for a more consistent linked resources interface. The resource/property filter should contain expected options and the linked resources table should reflect the order and content of whatever filter is selected. (Note that this does not fix the "linked resources for item sets" issue that came up recently.)

**Comment by allanaaa** [comment]
This seems to fix the most immediate problem, that the table was sorting and inserting subheadings based on resource templates. 

The pagination variable hostage-taking isn't fixed in this, if that's what you mean by "for item sets". 

On the admin side, the table could use space a bit better - instead of having each column be half the width:

<img width="848" alt="Screenshot 2024-04-16 at 10 32 02" src="https://github.com/omeka/omeka-s/assets/28012148/72e33005-3bf1-4307-961e-df6cea20e5ce">

That's all I'm really seeing.

**Comment by jimsafley** [comment]
Thanks for looking at this. There's another branch that fixes the hostage-taking: [linked-resources-async](https://github.com/omeka/omeka-s/tree/linked-resources-async). You could also look at that one, but it's probably not going into 4.1.0, so it's not urgent.
