### ISSUE TITLE
Why separate SiteAdmin from Admin controllers?

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#289]
I see no reason to separate site administration controllers from other administrative controllers. Years ago we assumed that site admin would live in a different route than other admin stuff, but that hasn't happened.

@zerocrates Why should this separation continue?

**Comment by zerocrates** [comment]
In decreasing importance:

- interia (as in, we need a reason to change it instead of a reason to keep it the same)
- potentially improves clarity, the SiteAdmin controllers use routing that's different from all the regular admin routes. this doesn't require giving them a different namespace but having the separation does make it obvious that they're handled differently somehow
- parallelism with the public-side Site controllers which *do* need to be separate
