### ISSUE TITLE
Executing an empty search in the simple search bar only returns a few resources

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#296]
likely ones that have no values.

**Comment by zerocrates** [comment]
I actually initially thought the problem here was that it was only returning resources (media specifically) that *did* have values, but that's not correct. It's also not returning ones without any values, so it's doing something different.

The underlying issue, regardless, is probably that we're trying to do a search even with an empty string term.

**Comment by jimsafley** [comment]
I'm seeing the same bug. It's strange that when I query the database directly, using the same SQL, I get zero results.

**Comment by jimsafley** [comment]
This query returns all items, as expected:

```sql
SELECT r0_.id AS id_0, 
	r0_.is_public AS is_public_1, 
	r0_.created AS created_2, 
	r0_.modified AS modified_3, 
	r0_.resource_type AS resource_type_4, 
	r0_.owner_id AS owner_id_5, 
	r0_.resource_class_id AS resource_class_id_6, 
	r0_.resource_template_id AS resource_template_id_7 
FROM item i1_ 
INNER JOIN resource r0_ ON i1_.id = r0_.id 
INNER JOIN value v2_ ON r0_.id = v2_.resource_id 
WHERE v2_.value LIKE "%%" 
ORDER BY r0_.created DESC, r0_.id DESC 
LIMIT 25 OFFSET 0
```

My installation has 2546 items, but when I search on an empty string `LIKE "%%"` or a one character string `LIKE "%a%"` the browse renders 3-7 items on a page. I suspect that doctrine bugs out on large result sets, but I'm puzzled how it affects pagination.

**Comment by zerocrates** [comment]
For me this seems to be definitely affecting the number of results and not the pagination limits, but maybe I just don't have enough items to see the pagination problem.

As we're not using Doctrine's paginator anymore, I think it's less likely that there's a limit/offset problem, but it's possible

**Comment by zerocrates** [comment]
Also, is that the query we're actually using there? that would definitely cause a few problems for sure: 

1. it's not doing DISTINCT, GROUP BY, or a WHERE IN subquery, so it will return duplicate results for every value that matches the query. That's probably what's messing with the pagination for you: it's not that the limit has changed, but that there are actually a bunch of duplicate results for every resource.
2. A "%%" search like this definitely won't get you all items, just all items with values (since they're being INNER JOINed). An inner join is fine for this query, but we do need to just skip it if the query term is blank.

**Comment by jimsafley** [comment]
That is the actual query being used there.

**Comment by zerocrates** [comment]
okay, that's definitely broken then

**Comment by jimsafley** [comment]
fixed in c47757eb3d8ed37fa6862d91f7f2ae4c47582848

**Comment by zerocrates** [comment]
This doesn't look like it solves the "original" problem, that executing a blank search only returns results for resources that have at least one value.

**Comment by jimsafley** [comment]
Are you suggesting that the search shouldn't accept an empty string? Or something else?

**Comment by zerocrates** [comment]
Yes, we should probably just ignore searches with empty terms
