### ISSUE TITLE
Allow modules to add to the item/resource show

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#322]
This could be in the form of a tab, direct addition to the page somewhere, the sidebar, or some combination thereof.

Needed by at least Mapping

**Comment by zerocrates** [comment]
This is possibly in the same realm as #177

**Comment by patrickmj** [comment]
Sounds like the same realm as #177 to me, at least the way I was thinking of it. 

A combination sounds good to me. For example, links back to the imported DSpace or Fedora item make much more sense as sidebar content, whereas a map sounds more like main page content most of the time, but maybe a tab.

And, multiple possible places in the page (maybe also the sidebar) sounds good, since we often enough hear questions about moving plugin content around the page. That might lead us into the territory of what themes can and cannot do. For example, do we have a concept of 0, 1, or 2 column themes, and therefore a need to give theme builders standard ways to handle that kind of distinction?
