### ISSUE TITLE
Batch updating?

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#326]
While it's a good idea, `batchUpdate` comes with its own problems. For one, should there be an error in the middle of a batch, there's no way to revert to original state. We do this in `batchCreate` by removing the non-persistent entities and leveraging their `postRemove` lifecycle events, but we can't do the same for persistent entities because `postRemove` has no concept of state (e.g. all files will be unlinked, not just files saved during the batch update).

If we don't care about reverting, we could do what `batchCreate` did before and fail silently, but we really want to avoid that outcome.

**Comment by zerocrates** [comment]
I'm not sure it's accurate to describe `postRemove` as being a problem here. The problem is more one of getting the remove(), and therefore the postRemove, to happen at all if we just refresh() or otherwise roll back the parent Item.

I think we're on the same page, I just want to make sure there's clarity in how this is described.

**Comment by jimsafley** [comment]
But we don't want `postRemove` to happen, do we?

**Comment by zerocrates** [comment]
I don't think that postRemove is the problem here. Maybe we're not on the same page after all. You definitely _do_ want postRemove to happen for any Media that got added during the update, if you're trying to be consistent with what batch create does. postRemove doesn't need any concept of state, it only operates on one Media at a time anyway, there doesn't seem to be any possibility of having the postRemove bleed over into other media/files.

The only question I have is whether the combination of refresh() and orphanRemoval will actually get those new Media removed. I'm not sure that it will. In other words, I don't think the postRemove event itself really matters much here, it's just whether remove() will get called at all.

**Comment by jimsafley** [comment]
Unfortunately `refresh()` does not invoke `remove()` on orphaned objects, so that solution is a no-go.

**Comment by zerocrates** [comment]
This version of batchUpdate is complicated for the reasons set forth above.

However, the user-facing feature of batch updating wouldn't quite be the same: it's about taking one set of metadata and updating that into some set of IDs or search results or whatever. In particular, that feature likely wouldn't allow you to create new Media for items as part of batch updating them (as creating identical Media for many items doesn't really make sense often).

So, we can effectively do some sidestepping of the problems we're seeing with this more "pure" batch update by making one that's more limited and tailored to what we'd want to expose to users in the interface.

**Comment by zerocrates** [comment]
Meeting on Friday the 10th

**Comment by zerocrates** [comment]
The original issue here pertains to a batchUpdate like batchCreate, which wouldn't have been that useful in the UI anyway. The more familiar feature of applying one same set of changes to many records is in #864
