### ISSUE TITLE
Allow modules to alter interface/backend for properties

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#361]
Somehow. This could work with the templates, with the value types, or as an entirely separate piece of functionality.

**Comment by jimsafley** [comment]
When editing a resource template an administrator can set a property's data type. Data types will be services like block layouts that include methods to:
* get value form markup
* validate input value
* transform value in (filter for storage, maybe not necessary now)
* transform value out (filter for rendering, maybe not necessary now)

**Comment by jimsafley** [comment]
A WIP in https://github.com/omeka/omeka-s/tree/data-types

**Comment by jimsafley** [comment]
@sharonmleon @sheilabrennan @zerocrates @patrickmj 

Before I continue this issue we need to discuss what should happen when a user changes the resource template on a resource add/edit page. Currently we allow changes willy-nilly because there's no reason for us to intervene. Now, with data types, we must intervene because there's no feasible way to transform data from one type to another when the template changes. I see two options:

* Refuse to change the template if there's anything filled in for a property whose data type will change;
* Allow the change, but only after warning that we'd throw away the data in those properties when saved.

For both it'll be the responsibility of the user to manually map between types. How would *you* like this to work?

**Comment by patrickmj** [comment]
Second option makes most sense to me -- keeping some data is better than keeping none, and I would bristle at being forced to start over for deep-down tech reasons. 

Is it possible to identify somehow what information will be thrown away and show it to the user? Something akin to a confirm modal?

**Comment by sheilabrennan** [comment]
This is tricky. 

What I would like is the refusal to change, with a notification that tells me what needs to be done in order for the change to happen.  Is that asking too much?

**Comment by patrickmj** [comment]
Partly we agree -- notification of details about what would need to be done (the property-value pairs) should definitely be there. But refusal seems extreme. If I have 5 property-value pairs that will roll over just fine, and 1 that won't, no reason to re-enter those 5 values.

If I'm understanding right, there's a lot that won't likely be an issue. dcterms:title and dcterms:description, for example, are very unlikely to have a datatype change, and are likely the most important things. I want to make that conversion as smooth as possible.

**Comment by patrickmj** [comment]
@jimsafley Can a resource template be updated in a way that would invoke the same questions?

**Comment by jimsafley** [comment]
@sheilabrennan For the "refuse" option, the notification would need to say something like:

> In order to change the resource template to "My Template" you first need to remove all the values in the following properties and manually re-enter them in another edit: dcterms:subject, dcterms:identifier, [etc.]

Not convenient but it discourages changing the template (which I see as a benefit).

For the "allow" option, the notification would say something like:

> You've changed the resource template to "My Template" but the values in the following properties will be deleted unless you manually change the current data to the new data type: dcterms:subject, dcterms:identifier, [etc.]

In the form, the affected values will show up using the new data type markup, but empty. Under each we'll display the raw data for the user to manually map to the new data type. While more convenient, it requires more intervention on our part.

Of course there could be other solutions that escape me.

**Comment by jimsafley** [comment]
@patrickmj That's a question I haven't considered. I can't think of a way to do this off the top of my head. There is a chance of corruption should the data types be incompatible.

**Comment by sharonmleon** [comment]
I tend to like the "allow" option better. It seems like it's more work, but offers more flexibility. 

@jimsafley Do you see significant disadvantages to this option?

**Comment by jimsafley** [comment]
@sharonmleon I see no *significant* disadvantage to the "allow" option. There are some things to consider, though. First, if a user changes some value then changes the resource template, the changed data would be discarded in favor of the saved data for manual mapping. Second, if the user changes the template and then switches back to the original, we cannot save the original state, i.e. the user would still have to map the data to the original data type (or just cancel out of the form).

**Comment by sharonmleon** [comment]
@jimsafley On the first issue, can we trigger an unsaved data warning before the template change?

The second seems logical and not unexpected to me.

**Comment by patrickmj** [comment]
Here's the most extreme, but I think plausible, scenario I see to consider (please correct me if I'm misunderstanding something):

A research project, when getting started, develops a resource template that seems to match their data (at least initially)

After 20, 50, 100, whatever resources are entered, they get to know their data better, and realize that the resource template should be revised, and that revision includes a change to the datatype for some property (say, dcterms:relation has a change, and a few other dcterms properties are in the template, but unchanged).

Going with the original premise of _changing_ resource template, and skipping the complication I introduced of editing the template itself....

Say original RT says dcterms:relation has datatype Text String.

But, in data input someone goes beyond the template, so that there are some dcterms:relation that are strings, and additional dcterms:relation that are URIs (or whatever other datatype)

Then, the revised RT says dcterms:relation has datatype URI (or whatever).

When they get to the fun task of changing the RTs from original to revised for data already entered:

Would the compatible prop-value pairs all be automatically mapped over, and warning given about all the incompatible prop-value pairs?

[the variations here sound hard]

**Comment by jimsafley** [comment]
@patrickmj You bring up good points. Those scenarios are plausible and troublesome.

There is a chance for the data to be corrupted if a user updates a resource template with a different data type. This is because the change happens outside the individual resource edit forms, so there's no opportunity for the user to manually map the data. I can think of no way to map the data automatically. As you say, the variations are hard.

**Comment by zerocrates** [comment]
What are we doing in this situation now, for Omeka 2 with Simple Vocab? The particulars are a little different but it's the same kind of problem: you can go apply a controlled vocabulary to a property after a bunch of data entry has happened, then you go back to edit some old item with data that's not in the vocab and... then what?

I assume in the Simple Vocab case you're just silently losing that value.

**Comment by jimsafley** [comment]
@zerocrates From the plugin:

> Existing texts that are not in the vocabulary will be preserved — however, they cannot be selected in the item edit page, and will be deleted once you save the item.

**Comment by jimsafley** [comment]
@sharonmleon @sheilabrennan @patrickmj

An altogether different solution to this is to reconfigure things internally so that any change to the template (whether it's switching templates or changing a data type) only affects new values; existing values will remain whatever type they are. If a user really wants to move existing data over to a new type they still need to manually do it, but they have the luxury of not *having* to do it.

@zerocrates and I prefer this approach than the two I proposed above. What do you think?

**Comment by patrickmj** [comment]
Yep. I like that better. If possible, some kind of message about the effects (e.g., which resources are affected, maybe even with the affected properties) would still be a nice bonus, but less critical in that scenario.

**Comment by sheilabrennan** [comment]
That sounds good to me.

**Comment by sharonmleon** [comment]
Sounds good to me.
