### ISSUE TITLE
Add site and site page show templates

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#376]
Currently on the admin side we have no *show* templates for site and site page—they are all add/edit forms. Since it is possible that logged-in users can view sites and site pages but don't have permission to administer them (see #366), we're going to need admin templates that contain no forms

**Comment by zerocrates** [comment]
Don't see why we need an admin-side show, can't we just link over to the "real" show on the frontend?

**Comment by jimsafley** [comment]
You're right, we can do that for "viewers", but what about "editors"? Editors should be able to get to page creation and editing, but right now they have to navigate there via site edit. At the very least we need a site show page.

**Comment by patrickmj** [comment]
I'm a little torn, but I'm tending toward having an admin-side show, at least as some sort of summary or overview. 

I'm thinking of an instructor or a manager (editor or admin) who wants to scan through the work on a site on the admin side. Just snippets or summaries of sites and site pages would suffice for 'show' there (especially since the details of how it looks on the public side would not be there on the admin side). That is, instead of _all_ the content, just put the structure in an admin-side show page, and if they want to see details, they either go to the public side or go to the edit screen. 

Currently, we sometimes get requests for an easier linkage between the public view and the admin viewing and editing (recent request like that is in the forums). WP handles this akin to John's approach -- a public page with an 'Edit Post' link in the top bar when logged in. But the structures of content we'll be dealing with seem sufficiently more complex to warrant an admin-side structure overview with the edit link on that side.
