### ISSUE TITLE
Templates for editing navigation pages

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#386]
We need some template markup for editing navigation pages:

* preset page (page created for a site)
  * page slug and page title (read only)
  * label field
* special page (page with special handling, e.g. browse, home)
  * page type (read only)
  * label field
  * place to put custom fields
* custom page
  * label field
  * url field

Ideally, there shouldn't be much variation between the templates. Once I have the templates I'll integrate them into the interface.

**Comment by kimisgold** [comment]
In the markup, there should be a button for toggling the editable fields. Ideally something like this within `.jstree-anchor`. 

`<i class="jstree-icon jstree-editnode" role="presentation"></i>`

**Comment by zerocrates** [comment]
So, I've asked this before, but I just want the answer somewhere where I can come back and refer to it: I know JSTree has some support for making the "row" itself editable. Since editing the label for each link is always going to be an option, what's the reason for not using that functionality for the label part? That would mean being able to avoid the "expand to show fields" button for all the "regular" pages as there wouldn't be any extra fields to show.

**Comment by jimsafley** [comment]
I don't think I answered this, but for now I want to make things simple for me. Maybe I could do what you suggest, but that will come later.

**Comment by kimisgold** [comment]
The editable fields for a 'custom url' node should be visible upon adding the node to the nav tree. To do this, the node should have class "jstree-editmode" and `show()` the node's `.jstree-editlink-container`.
