### ISSUE TITLE
Style read-only site information on site edit

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#412]
General, read-only site information in the \#admin panel the needs to be styled.

**Comment by kimisgold** [comment]
So we currently have a 'show' view for sites, specifically for roles that can only edit pages. The site/browse view currently links 'editor' roles to the site 'show' view and 'administrator' roles to the site 'edit' view. For reference, here are the differences between the two views:

<table>
  <thead>
    <tr>
      <th>Actions</th>
      <th>Show</th>
      <th>Edit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>View uneditable site slug, title, theme</td>
      <td>yes</td>
      <td>no</td>
    </tr>
    <tr>
      <td>Edit slug, title, theme</td>
      <td>no</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>View list of pages and link to page/edit</td>
      <td>yes</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>Add new pages</td>
      <td>yes</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>Delete pages</td>
      <td>no</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>Edit site navigation</td>
      <td>no</td>
      <td>yes</td>
    </tr>
    <tr>
      <td>Edit user permissions</td>
      <td>no</td>
      <td>yes</td>
    </tr>
  </tbody>
</table>

1. Should we have distinct link buttons for site 'edit' and 'show' views?

2. Do we need to set up routes/permissions so that 'editor' roles cannot access the 'edit' view?

**Comment by jimsafley** [comment]
> Should we have distinct link buttons for site 'edit' and 'show' views?

Do you mean distinct icons for the two in browse rows? If so, yes.

> Do we need to set up routes/permissions so that 'editor' roles cannot access the 'edit' view?

I suppose there's no need since there's no edit link and there's already protections in place to prevent an editor from doing anything they shouldn't.
