### ISSUE TITLE
Adapt sidebar functionality for mobile widths

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#472]

**Comment by kimisgold** [comment]
This feature is ready to test. Checkout the `mobile-sidebar` branch and test the following:

* On the `browse` views, tap the `...` buttons to view more details.
* On the `resource/edit` views, tap the 'Add Property' button to use the property selector sidebar.
  * Close the property selector sidebar without choosing a property.
  * Choose a property from the sidebar, see that it is added to the form, and the view scrolls to the new property field.
* On the `resource/edit` views, add an Omeka Item or Item Set as a resource value.
* On the `resource/edit` views, toggle between the sections: 'Values', 'Media', and 'Item Sets'. (Do not try using the media drag'n'drop, as it doesn't work and will eventually be its own separate issue.)

@mebrett @sheilabrennan @sharonmleon @kalbers

**Comment by mebrett** [comment]
Everything works. However, when you select an Omeka Item or Item Set as a resource value, the sidebar goes back to being "Select Resource" and not back to resource/edit. You have to X out of the sidebar to see that the resource has been attached, which is a little confusing. 

The triangle arrows on the section labels 'Values,' ;Media,' and 'Item Sets' make me want to be able to toggle them to collapse the section - especially values as it can be so long. I don't know if this is a generally expected behavior or just something I'm expecting based on how we used the same icon in Exhibit Builder.

**Comment by mebrett** [comment]
On resource/edit, the header for Media sometimes extends off the page once toggled open. I think it has to do with the length of the media filename (those which are super long cause the over extension)

long file name: 
![screen shot 2016-01-20 at 2 55 23 pm](https://cloud.githubusercontent.com/assets/2314070/12461576/a8b8de6e-bf87-11e5-98e6-4279099fc5ea.png)

short file name: 
![screen shot 2016-01-20 at 3 08 11 pm](https://cloud.githubusercontent.com/assets/2314070/12461586/b38a08f4-bf87-11e5-9158-2f947c16bc07.png)

**Comment by kimisgold** [comment]
@mebrett Just addressed your feedback in the most recent commit to the branch, so now sidebars should automatically close once you've made a selection, and fieldsets/sections are expandable and collapsible in what I think are more expected behaviors.

**Comment by mebrett** [comment]
Thank you for making the sections collapse. Looks great.
