### ISSUE TITLE
We should do something useful with the admin dashboard

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#527]
Does it make sense to do something with Sites here? (Even possibly having the sites browse be the front page of the admin?)

We can have a stats-type page like we do in classic, but I'm not sure how useful that really is. The idea of having the sites be there comes from two places: 1: it's parallel with the "default" frontend page, 2: we don't have a link that goes to the frontend right now besides the ones for each Site (which makes sense, I think, but maybe we want to push those more to the foreground)

**Comment by kimisgold** [comment]
Could we display a single list of most recently edited records? Not in the sections we currently have in classic, but all together with actions to continue editing or create a new record as well as user and date info since we're probably going to see a lot more collaborative work in S. Something like:

| Modified object           | User    | Date                       | Actions                     |
|---------------------------|---------|----------------------------|-----------------------------|
| Site page: "Lorem ipsum"  | admin   | January 6, 2017 at 5:15pm  | Edit page • New page        |
| Item: "Commodo Egestas"   | student | January 6, 2017 at 4:34pm  | Edit item • New item        |
| Zotero Import             | admin   | January 5, 2017 at 10:13am | Browse imports • New import |
| Site page: "Pellentesque" | admin   | January 5, 2017 at 10:10am | Edit page • New page        |

Alternatively, we could create a user setting that would allow individuals to set their default landing page? Like you could set `item/browse` or the `site-page/browse` if you know you're going to be working primarily in those areas. The initial landing page could be the user account view where you'd be able to assign that setting.

**Comment by zerocrates** [comment]
User settings we don't have at all so that'd be a whole thing on its own (not necessarily a bad idea, but this probably isn't the feature that would justify its addition).

We also probably can't easily interleave "most recent" stuff from across different kinds of records.

**Comment by kimisgold** [comment]
You're no fun.

**Comment by patrickmj** [comment]
Is it worth thinking about different dashboards for the global admin vs everyone else? Is there data that the global admins would want quick access to that wouldn't really apply to others?

**Comment by zerocrates** [comment]
Potentially links to the major areas? (global pool, site, other.....)

Goes hand in hand with moving around the nav to reflect same divisions probably.

**Comment by jimsafley** [comment]
![20160304_121435](https://cloud.githubusercontent.com/assets/141955/13534722/969d4112-e204-11e5-98dd-ff37c3242c57.jpg)
