### ISSUE TITLE
Provide feedback on 'file' site page block

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#555]
We're currently debating the merits of the "file with text" block layout, which is essentially the HTML block with the ability to attach omeka resources. In the `file-layout` branch, we've separated out the resource attachment interface into its own 'file' block layout. We'd like testers to build pages using the 'file' and 'HTML' blocks and describe their experiences. A few sample questions to answer:

* When first using the 'file' and 'html' blocks, does the public page display as you expect?
* Do you feel much difference between the combined block versus the separated blocks?
* Do you see a need for both the "file with text" and "file" blocks?

**Comment by aodiorne** [comment]
- I might have expected large thumbnail to be a bit larger.  

- I don't think I 'feel' much difference, but it does seem like I have more control if that makes any sense.

- Yes, I could imagine that it would be useful when working with different themes, or when people are building themes they might be able to allow the elements to align differently.

**Comment by alyssafahringer** [comment]
- The HTML block does display publicly as expected
- When adding attachment to a file block, I frequently forget to click the 'apply changes' button 
- There doesn't seem to be a difference in the medium and large sizes of the thumbnail when attaching an item in the file block 
- I prefer the separated blocks because I like the item to be separate from the text. When creating the Martha Washington test site, I used HTML and file blocks rather than file with text blocks because I preferred for the image/item to either be on top of or below the text, rather than integrated within the text
- But, as Andrea pointed out, both file and file with text blocks can be useful depending on what users are creating

**Comment by mebrett** [comment]
I feel like I can see use cases for having file with text in addition to the separate File and HTML blocks, although some of those might be mitigated by site admins making it very clear to their users (students) what to do. The layout is not, however, precisely similar. 

I'm having the same problem as Alyssa with the file size not changing despite choosing large or medium (in fact, it sometimes loads smaller than thumbnail, and the title is doing odd wrapping things: 
![screen shot 2016-03-22 at 4 18 56 pm](https://cloud.githubusercontent.com/assets/2314070/13967380/2837b71e-f04d-11e5-9744-be6529bc6de9.png)

**Comment by kimisgold** [comment]
The image sizing should be fixed in 331793a699acdfc16121b7f2e97c79642f921e43.

**Comment by alyssafahringer** [comment]
There is now a noticeable difference between the medium and large file sizes when attaching an item in the file block.

**Comment by LaceyWilson** [comment]
The medium and square sizes are exactly the same.

**Comment by kimisgold** [comment]
I'd like further feedback regarding the uses of the 'file' versus 'file with html' block. What do testers perceive as the functional difference between the two blocks? What are specific use cases for one block over another?

**Comment by LaceyWilson** [comment]
I think the file and text blocks being separate are better. There is more control on where files can be and it allows for the text to continually wrap around the files. On my test page I did the top part with file and html blocks. The bottom part was done with two file with text blocks.

http://dev.omeka.org/omeka-s/s/doctorwho/page/test

**Comment by alyssafahringer** [comment]
I prefer having only the HTML and file blocks, rather than having those two options in addition to file with text. Having the two separated make more sense to me, especially when compared with the other options available to users (browse preview, item showcase, etc.). Personally I do not see the advantages of using file with text when I can use file and HTML separately. I prefer to keep the text and item separate rather than integrate them into one option, and HTML and file display on the front end the way I would like them to, and file with text does not.

**Comment by kimisgold** [comment]
It sounds like the file-only block is more straightforward and useful, so we're going to replace 'file with text' with just 'file'.
