### ISSUE TITLE
Media playback from Vimeo displays with extra black space

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#609]
Videos created as media via oEmbed are display on public and admin pages with a lot of extra black space on top and bottom. Other oEmbed videos look fine.

See: Youtube, Vimeo, and TED talk videos on this page: http://dev.omeka.org/omeka-s/s/my-cool-site/page/page

**Comment by zerocrates** [comment]
The issue here is with our resizing of rendered iframes and the way browsers handle that. An img, we can set height: auto and it'll maintain its aspect ratio. iframes will just squash whatever direction we try to constrain.

We can probably try to fix it with javascript, as the script can see what the "real" aspect ratio is supposed to be and calculate the correct height from that.

**Comment by zerocrates** [comment]
You can try out the iframe-aspect branch which adds a little javascript that hopefully deals with this.

**Comment by mebrett** [comment]
That fixed it on the admin and public item view (http://dev.omeka.org/mebrett/testomekas/s/publicviews/item/3627) but not in the media display blocks on public pages (http://dev.omeka.org/mebrett/testomekas/s/publicviews/page/video-playback)

**Comment by zerocrates** [comment]
Yeah, it's not applied to the public side in that branch yet

**Comment by zerocrates** [comment]
Pulling on that branch should get you a version where it's also fixed on the public side.

**Comment by mebrett** [comment]
It does indeed. Thank you.
