### ISSUE TITLE
Should the property search show vocabs with no matches?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#703]
Editing an Item, put 'abstract' into the property search input. It happily reports back the matches in dcterms: and bibo:, but also says no results in the other vocabs.

Should we display the lack of results in the vocabs, or should we make the 0 results disappear altogether?

(I have a feeling we've thought about this before, so forgive me if I'm going over well-trodden ground)

**Comment by zerocrates** [comment]
So I'm clear: you're suggesting that we just hide the sections for vocabs with no results, rather than show them with a zero count?

Doesn't make much difference to me... I can see the argument that it accentuates the results and it's fine by me if we want to do it that way. We'd probably need some special handling of the case where there are no results from any of the vocabs, though.

**Comment by patrickmj** [comment]
Yep, hide vocabs completely if count is 0. 

Showing vocabs with count 0 seems like clutter when I'm doing a deliberate search to narrow down results. It gets more noticable the more vocabs are installed, like when you import the vocabs that go along with FedoraConnector. Since we make it easy to import other vocabs, I can see that clutter adding up quickly.
