### ISSUE TITLE
Consider letting resource templates designate a property as required

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#719]
It's common enough for an institution's workflow to mark certain properties as required, and appears in requirements lists for adopting a system.

**Comment by jimsafley** [comment]
This is a WIP in https://github.com/omeka/omeka-s/tree/required-properties It includes sever-side validation.

One thing that would be nice is client-side validation. Ideally we'd do this using HTML5's "required" attribute, though we can't take for granted that data types have inputs or textareas to flag as required. (Hidden inputs cannot take the required attribute.) Another way is for data types to attach a handler to some event that validates the first non-deleted field in the required property's fieldset, resulting in an aggregated alert on submit. Not pretty, but it would get the job done.

**Comment by jimsafley** [comment]
Implemented client-side validation in 136f714d5981a60ab6b997498b030ea3836c0c1d but one question. Right now we assume that a required property *IS NOT* valid until the data type handlers flag at least one value as completed. Instead, should we assume that a property *IS* valid until the data type handlers say otherwise? The way we currently handle it, if a data type does not implement `o:check-required-value`, the form will never validate.

**Comment by patrickmj** [comment]
Good and interesting question. 
If I follow right, I lean toward the latter, 'instead', option -- just requiring that _something_ is there, and not worrying about datatypes as far as possible.

**Comment by zerocrates** [comment]
What Jim's got there works but I'd prefer if we could come up with some way to do it more automatically. Data types previously had required scripting for each one and I'd really prefer not to have to go back to that. You get things like having to manually duplicate the scripting for a subclassed data type, because the identifier is different so the existing script won't work even if the logic is the same.

With the previous scripts, we got rid of the necessity of having them by adding data attrs to the elements that the code knew to look for to do things like fill in and read out the appropriate parts of the value object. Can we just add a data attr or class for "this is the thing that needs to be filled in", then have one generalized "required" check just look through all of those for each "required" property? Then we don't need custom scripting for each, and it should still work, even with the "problematic" form elements like hiddens.

**Comment by jimsafley** [comment]
@kimisgold Each property in the resource template form has a new "Required" checkbox. It's going to need styling.
