### ISSUE TITLE
Consider creating a checksum for ingested files

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#720]
Some convo with John made this sound like it wouldn't be too big a change, and that we have this in Classic

**Comment by jimsafley** [comment]
Some reading on the issue:

* https://www.wikiwand.com/en/File_verification
* http://security.stackexchange.com/questions/87375/why-are-md5-and-sha-1-still-used-for-checksums-and-certificates-if-they-are-call
* http://stackoverflow.com/questions/14139727/sha-256-or-md5-for-file-integrity

Most compelling is the first link: "As of 2012, best practice recommendations is to use SHA-2 or SHA-3 to generate new file integrity digests".

**Comment by zerocrates** [comment]
On the other hand there's http://www.dpconline.org/technical-solutions-and-tools/fixity-and-checksums

> There are several different checksum algorithms, e.g. MD5 and SHA-256 that can be used to generate checksums of increasing strength. The ‘stronger’ the algorithm then the harder it is to deliberately change a file in a way that goes undetected. This can be important for applications where there is a need to demonstrate resistance to malicious corruption or alteration of digital materials, for example where evidential weight and legal admissibility is important. However, if checksums are being used to detect accidental loss or damage to files, for example due to a storage failure, then MD5 is sufficient and has the advantage of being well supported in tools and is quick to calculate.

**Comment by zerocrates** [comment]
MD5's brokenness really only matters if the intent is to protect against malicious tampering rather than accidental corruption.

On the other hand as you see in those Q and A type answers, the fact that it's "broken" leads to strong opinions. There's nothing *wrong* with using sha256 (sha-2), it's just sort of a judgment call. The downsides are speed (probably not worth worrying about) and space (the column must be larger, as well as the hex representation when we want to show it. The potential upside would be better tamper resistance (or rather better possibility of detection, since we just passively hold the checksums).
