### ISSUE TITLE
Add Another Item Button

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#740]
When in the process of adding items by hand, the workflow after hitting the Add button pushes the user to a admin item show page. It would be nice if we could find a space on that screen for an [Add Another Item] button. 

The system can definitely tells the stage in the workflow because it prints the green "Item successfully created" banner.

**Comment by zerocrates** [comment]
Within the banner itself as a link might be the easiest/most consistent option

**Comment by sharonmleon** [comment]
That would be great.

**Comment by zerocrates** [comment]
I'm thinking we just want to put it into the flash message from the add action, so there wouldn't technically be any change to any of the shows.

As to whether to do it to other adds, I suppose for consistency's sake we'd want to do it to all of them. At least items, sets, site pages, possibly sites seem like this would be potentially useful for. Probably easiest to just do it as a matter of course rather than case-by-case.

**Comment by kimisgold** [comment]
Ah, I misread and thought the banner was the page actions. This makes more sense.

**Comment by kimisgold** [comment]
The issue's blocked for now, as there doesn't currently seem to be a way to add unescaped html to the messenger banner, resulting in this:

<img width="654" alt="screen shot 2016-09-19 at 1 51 17 pm" src="https://cloud.githubusercontent.com/assets/606764/18642812/2f3e17a4-7e70-11e6-9923-1007901f11e9.png">

**Comment by zerocrates** [comment]
What we need to add is a way to opt out (and it should be opt out, not in) from escaping of the message (meaning we'd have to be sure to create and escape it correctly ourselves when using it).
