### ISSUE TITLE
Invalid argument on item-set-advanced-search

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#748]
Created an item set with no title, then went to advanced search from the set's item list

```
Warning: Invalid argument supplied for foreach() in /var/www/omekas/application/view-shared/common/item-sets-advanced-search.phtml on line 6
```

**Comment by zerocrates** [comment]
Confirmed: it happens whenever you go to item advanced search with an item_set_id specified in the query string.

**Comment by zerocrates** [comment]
Actually the issue is that the links generated for "view items in this set" specify a single set: item_set_id=X, but the view is expecting item_set_id to be an array. The simplest option might be to remove the ability to search by just a single value, and force it to be specified as an array. The existing links can easily just wrap an array around the ID they're passing to the query string.

Alternatively, we'd just need to detect a single scalar arg for this in the view and wrap it into an array.

**Comment by zerocrates** [comment]
On second thought this needs to handle the "isn't actually an array" state regardless, so it might as well just keep the current behavior and fix the handling of getting a scalar.
