### ISSUE TITLE
Stablize Omeka\Event constants

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#768]
As I've  been working through both the more-events branch and documentation, I've come across a bunch of events being triggered that aren't included in the Omeka\Event list of constants. I'm adding them in the more-events branch as I go along, but I'm not sure that's useful.

We should decide whether all events are explicitly listed as constants there, or whether they will be documented elsewhere as needed.

**Comment by jimsafley** [comment]
We only need `Omeka\Event\Event` because of a few places that use the constants. The class provides nothing else. In fact, I'd like to see it removed, constants and all. But to do so would require searching through the core and module code for occurrences of the class and changing event names to strings.

Remove our superfluous `Event` class. It's best to document the events elsewhere.

**Comment by jimsafley** [comment]
Note: if we are to remove the class it'll be best to do it before we release beta.

**Comment by patrickmj** [comment]
Yep! Definitely something for before beta release, which is why I was curious about it. I can remove it on the `more-events` branch and search through the code base removing references. There are few places that I've seen using it.

**Comment by zerocrates** [comment]
Patrick asked me about this earlier and I counseled leaving it alone but it wasn't clear to me that there's just _nothing_ but these constants in that class, which is pretty silly.

**Comment by patrickmj** [comment]
Sounds like consensus is to clobber the class, then.
