### ISSUE TITLE
Advanced search link broken on public site (item-set action)

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#784]

**Comment by zerocrates** [comment]
The exact error here was being caused by some imprecise routing picking up more than it should have. That's fixed, but the actual item-set search action and view and everything don't actually exist, so it's now a more vanilla 404.

**Comment by zerocrates** [comment]
We can either fix this by adding the search page, which _shouldn't_ be too difficult since we have the item search already, or by removing the link here in the short term.

(note, this is *not* the same issue as the other very similar one about the search link on the item set *show* page, that one is fixed)

**Comment by sheilabrennan** [comment]
What is the resulting cascade by adding it? My instinct for now is to remove it for the short term.
