### ISSUE TITLE
Vocabulary "Bibliographic Ontology" (bibo) / MultiVolumeBook

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#822]
Hi,

There is an issue in `bibo.rdf` : there are two labels `Series`, one for `MultiVolumeBooks` (https://github.com/omeka/omeka-s/blob/develop/application/data/vocabularies/bibo.rdf#L2202) and one for `Series` (https://github.com/omeka/omeka-s/blob/develop/application/data/vocabularies/bibo.rdf#L2403). This is very confusing and this issue is not present in the current version of the vocabulary (https://github.com/structureddynamics/Bibliographic-Ontology-BIBO/blob/master/bibo.owl#L2053).

Can you refresh the vocabularies?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by patrickmj** [comment]
Thanks. Ironically, at least some of those oddities were fixed by us when we noticed them, but might not have made it back into Omeka S from the new `bibo` source file. 

I vaguely recall some conversation about how to handle updates to the external vocabularies and versioning. I suspect that new installations of S will try to keep up to date with the external vocabs, but I'm even less certain about how the updating process will work.

**Comment by Daniel-KM** [comment]
Anyway, it's something to change before the publication of the first final release of Omeka S.

**Comment by zerocrates** [comment]
We've pulled in the updated bibo.rdf, now called bibo.owl.

Right now the strategy is to update our copy (and therefore any new installations from that point on) but not automatically migrate already-installed vocabs for existing sites. To handle them and also changes to user-added vocabs, admins can now re-upload an updated copy of the vocab file on the edit page for a vocab and we'll process label changes and new properties/classes.

(See #848)
