### ISSUE TITLE
404 Error upon installation

### ISSUE THREAD

**Issue by brianmcbride** [omeka/omeka-s#826]
Followed the instructions as described on https://github.com/omeka/omeka-s for the zip download installation but received the following error when accessing site

GET /install HTTP/1.1" 404 299

Background info: PHP7, PDO support enabled, AllowOverride ALL, MySQL, Ubuntu 16.04 LTS.

**Comment by zerocrates** [comment]
It certainly sounds like an .htaccess problem. You mention AllowOverride is set to ALL, which is the correct value (though the usual capitalization is "All", you might want to try changing that if your actual setting is all uppercase, I'm not sure if the case is significant for that directive or not). Also make sure you have mod_rewrite installed and enabled, and make sure the .htaccess file is actually sitting in the top directory of your Omeka installation (sometimes people leave it behind when moving files around since it's a hidden file).
