### ISSUE TITLE
PHP being called from JavaScript

### ISSUE THREAD

**Issue by stephenwf** [omeka/omeka-s#845]
Composer has an extensive lifecycle of scripts available:
https://getcomposer.org/doc/articles/scripts.md

Including support for custom scripts run using `composer run {command}`. 

I was hoping to get some insight on the decision to write PHP in JavaScript with native alternatives readily available

**Comment by zerocrates** [comment]
The idea here is to make it so that we can generally present a single entry point to people needing to do buildscript-type stuff.

Given our desire to use autoprefixer among other things, and eventually tasks actually related to the Javascript code itself, we already need the Node tooling. So, I decided the best course of action would be to define all the tasks from our prior Ant script in the Gulp one, to remove the need to have the whole Java and Node ecosystems installed. Like the Ant script before it, the Gulpfile handles automatically downloading and self-updating a local copy of Composer.

We could reorient things so Composer is instead the main thing people install and interact with, but they'd have to basically run the same steps they do now to get the Node-based tools (`npm install,` minimally, installing Node itself, maximally), as we'd still need those. So, having Gulp be the entry point just simplifies things a little bit and allows us to write shorter instructions.

Ultimately, once a task is just running some command, it's fairly irrelevant which language does the spawning. A few things could be rewritten as just callbacks rather than scripts if we were using Composer's script/command functionality, but I don't think that's a particularly major improvement.
