### ISSUE TITLE
Usage of gulp 4.0 breaking builds

### ISSUE THREAD

**Issue by odetoignorance** [omeka/omeka-s#846]
Due to gulp 4.0 not having a release branch, this is breaking automated builds which rely on using stable releases of dependancies

Context:
`-npm ERR! git clone git@github.com:github:gulpjs/gulp Cloning into bare repository '/home/travis/.npm/_git-remotes/git-github-com-github-gulpjs-gulp-e2adb3d8'...`
`npm ERR! git clone git@github.com:github:gulpjs/gulp fatal: remote error: `
`npm ERR! git clone git@github.com:github:gulpjs/gulp    is not a valid repository name`
`npm ERR! git clone git@github.com:github:gulpjs/gulp   Email support@github.com for help`
`npm ERR! notarget No compatible version found: gulp@'github:gulpjs/gulp#4.0'`
`npm ERR! notarget Valid install targets:`
`npm ERR! notarget ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.7","0.0.8","0.0.9","0.1.0","0.2.0","1.0.0","1.1.0","1.2.0","1.2.1","2.0.0","2.0.1","2.1.0","2.2.0","2.3.0","2.4.0","2.4.1","2.6.0","2.6.1","2.7.0","3.0.0","3.1.1","3.1.2","3.1.3","3.1.4","3.2.0","3.2.1","3.2.2","3.2.3","3.2.4","3.2.5","3.3.0","3.3.1","3.3.2","3.3.4","3.4.0","3.5.0","3.5.1","3.5.2","3.5.5","3.5.6","3.6.0","3.6.1","3.6.2","3.7.0","3.8.0","3.8.1","3.8.2","3.8.3","3.8.4","3.8.5","3.8.6","3.8.7","3.8.8","3.8.9","3.8.10","3.8.11","3.9.0","3.9.1"]`
`npm ERR! notarget `

**Comment by zerocrates** [comment]
I'm not sure I understand the conditions this is failing under. I haven't seen this error reported by the few others I know have run the recently updated script, and I know it runs on Travis where our own automated tests get executed.

Perhaps it's a matter of different behavior from different versions of npm?

**Comment by zerocrates** [comment]
Ah, and now that I pay more attention, I see you're using Travis. It's almost certainly just that the old npm used by Travis by default doesn't understand the syntax being used by the more recent npm which created our package.json (in particular, it looks like it doesn't properly understand the `github:` prefix, as your error message indicates it thinks it's part of the repo name).

Travis defaults to a _very_ old Node on PHP builds. We use a small `before_install` in .travis.yml to switch to a current stable version. Since it's working for our own builds, I imagine it would work for yours:

```yml
before_install:
 - nvm install node
 - nvm use node
```

**Comment by odetoignorance** [comment]
seems to have done the trick, cheers
