### ISSUE TITLE
Batch editing for API resources

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#864]
Notes

- Scope: all resources (resource entities for sure, design against API resources to allow for extension to User, etc.)
- Selection
  - from browse pages
    - one-by-one (checkboxes on browse probably, limited to page size, checkboxes individually acl-checked)
    - all matches of current search/browse (run in background, simply skip records user doesn't have permission on) 
- Actions
  - All API resources
    - delete resource
  - All Resource entities
    - public/not
    - Resource Class
    - Resource Template
    - Add property value (leverage existing resource form)
      - literal
      - uri
      - internal resource link
      - Question: what to do about custom types (leverage selected template to apply, if selected?)
    - Clear property (delete all values)
      - should happen before adding new, probably
      - and/or "overwrite" flag on "Add property value"
    - Set owner?
  - Items only
    - add to/remove from Item Set
  - Item Sets only
    - open/not
  - Users (slightly more uncertain but greatly desired)
    - set role
    - activate/deactivate
  - Modules
    - should be able to extend Item actions etc., or add support for own added resources
    - either do through events or registering actions in merged config

General notes:
- should probably resolve search results up front in background job version: so changes to things that affect the search results don't affect the pagination and result in duplicates or skips, just hold in memory matching IDs from start
- probably the best/easiest implementation here is to have this just accept some subset of the API update data an individual record would take, along with the set of records to operate on, and then it just issues a PATCH to each. Could be implemented as an API resource of its own (a POST to "batch_update" resource?), or a service/layer that simply uses the API itself (then not accessible to API clients, but they could self-implement batching). Separate layer is probably simpler.
  - the batch updater should have some definition of what pieces of data are actually accepted, make sure people can't step around the UI and submit problematic data to batch (like new media)
- General sense is that permission to batch edit should perhaps be more restricted than general permission to edit
- My initial thought on UI is to have the main area of actions to perform start blank and then be filled up by selecting from a sidebar, so users don't have to scroll past a bunch of empty forms for flags and selections they're not using to get to the stuff they want, just a simple list of buttons that when selected cause the real form to appear (or just a simple line saying what will be done)

**Comment by jimsafley** [comment]
This is a WIP in the [batch_update](https://github.com/omeka/omeka-s/tree/batch_update) branch. 

Instead of working around the API, I've run with an implementation that introduces the new BATCH_UPDATE request operation. This is now possible, in part, due to [recent changes to the API](https://github.com/omeka/omeka-s/pull/861#issuecomment-287615678) that make batch operations more friendly. Furthermore, the addition of `processBatchUpdateData()` to the adapters gives them the opportunity to filter out problematic request data that previously made batch updating less desirable.

Right now, all BATCH_UPDATE operations execute as "isPartial" (PATCH) requests because of this need to isolate safe data from unsafe data. It works well for adding and modifying data, but it doesn't work well for removing data because our pattern for removing data assumes a normal non-"isPartial" (PUT) request. For example, clearing all values of a property is impossible without including all existing values in the request _minus_ the ones that need to be cleared. Removing items from an item set is a similar situation.

This is all complicated by the requirement that the passed data has to be valid JSON-LD. Otherwise we may be able to act on "remove" or "clear" flags embedded in the data during "isPartial" requests.

Another potentially tricky area is batch deleting resources. I'm not sure whether it's worth our time to implement a BATCH_DELETE operation. I don't know if there would be any advantage of that over simply iterating DELETE.

**Comment by jimsafley** [comment]
We may need to explore the idea that removing data should be done outside the API using a service/layer. While not accessible to API clients, it does make it easier to dictate the safest operation flow: remove first, then add/modify last. Of course, as mentioned above, clients would still be able to self-implement batch removal by iterating UPDATE.

**Comment by zerocrates** [comment]
I'm okay with the idea of deletion itself happening somewhat separately
(just a loop of existing DELETE, as you said) but I'm very uncomfortable
with the idea of partitioning out pieces of the "update" into different
areas.

**Comment by jimsafley** [comment]
Fair enough. Nevertheless, looking at the code extensively, I just can't find a way to reconcile BATCH_UPDATE's "isPartial", our existing pattern for removal, and JSON-LD compatibility.

**Comment by zerocrates** [comment]
I'll look at it more closely next week. If we need to we could probably pass in parallel information that the ValueHydrator can see, like a list of properties whose values should overwrite what's existing rather than add to it.

**Comment by jimsafley** [comment]
Yes, it seems that we can pass parallel data that doesn't invalidate JSON-LD. According to the spec:

> All keys which are not IRIs, compact IRIs, terms valid in the active context, or one of the following keyword must be ignored when processed... [[link](http://json-ld.org/spec/latest/json-ld/#node-objects)]

Meaning we could add something like  `"clear_property": [1, 2, 3]` to the input and process it during BATCH_UPDATE, prior to sending the data to ValueHydrator. (I don't think it's possible during value hydration without some significant rewriting.)

**Comment by jimsafley** [comment]
Something like this in `AbstractResourceEntityAdapter::hydrate()` may work:

```php
if (isset($data['clear_property']) && is_array($data['clear_property'])
    && $request->getOption('isPartial', false)
) { 
    $criteria = \Doctrine\Common\Collections\Criteria::create()
        ->where(Criteria::expr()->in('property', $data['clear_property']));
    $entity->getValues()->matching($criteria)->clear();

}
```

**Comment by jimsafley** [comment]
Hydrating entity collections during "isPartial" (PATCH) requests is currently broken. Instead of adding and removing specified data, we perform a replace/overwrite as if it was a normal update (PUT) request. Wrapping collection hydration with `shouldHydrate()` is not enough.

Users could add data to a collection by setting an "append" request option, but that a) introduces more complexity to a request already marked as "isPartial", and b) doesn't solve the data removal problem.

What I think is better is if users could pass parallel data with a PATCH request that specifically declares what to add to and remove from a collection. For example, during an item request:

```
"patch": {
    "resource_value": {
        "add": [valueObj],
        "remove": [propertyId] // clears all values of the property
    ],
    "item_item_set": {
        "add": [itemSetObj],
        "remove": [itemSetId]
    },
    "item_media": {
        "add": [mediaObj],
        "remove": [mediaId]
    }
}
```

We're already doing this for resource values, so there shouldn't be a problem extending it to all entity collections that we're hydrating.

**Comment by jimsafley** [comment]
@patrickmj In the [batch_update](https://github.com/omeka/omeka-s/tree/batch_update) branch, one change that will likely affect your modules is the new ["collectionAction"](https://github.com/omeka/omeka-s/blob/batch_update/application/src/Api/Request.php#L187-L192) request option.

Currently during UPDATE requests we append any passed values (e.g. dcterms:title) to the value collection. Now, with the changes in that branch, you'll need to explicitly set "collectionAction=append" to the request, otherwise we replace the existing collection with the passed values.
