### ISSUE TITLE
Editor placement for Welcome page text off in FF

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#894]
When editing the Welcome page for a site, the text box initially does not display the HTML editor. Clicking on the text area shows the editor, but it doesn't align correctly.

![wonkywelcome](https://cloud.githubusercontent.com/assets/153262/25410987/033dd1ca-29e8-11e7-96fc-3c1fa3ef69c9.png)

**Comment by kimisgold** [comment]
I'm a little confused, as this all seems to be expected behavior. To save space on the page, we opted to use the CKEditor inline option back in 44098786e925a174670d9bbadb527e102c102e47, so that the tools only appear when actively editing a field that supports HTML content. It's a hover menu (the default behavior for this CKEditor option), so I'm not sure what a correct alignment would be.

**Comment by patrickmj** [comment]
Alignment might be the wrong word, and it's hard to see in the screenshot.

The top of the CKEditor stuff ("Source", Link, and other top bar things appear on top of the URL slug input.

**Comment by kimisgold** [comment]
That's expected behavior—see CKEditor's examples of the inline editor: http://sdk.ckeditor.com/samples/inline.html. We could make it less awkward by making the toolbar take up the full width of the input?

**Comment by patrickmj** [comment]
Hmm....the width isn't what makes me raise an eyebrow. But from that example if the overlay is as it should be, I guess that's okay. Just seemed odd to cover up an input.
