### ISSUE TITLE
Logged-in indicator

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#900]

**Comment by patrickmj** [comment]
If we are going to go with anonymous users being able to switch languages, it seems like the place to make that switch might be very similar to how the logged-in indicator gets stuffed onto the page.

**Comment by elrossco22** [comment]
one to follow @stephenwf @euanfergusson

**Comment by mebrett** [comment]
@kimisgold particular branch?

**Comment by kimisgold** [comment]
* When logged in, a header bar appears above the page layout featuring links to:
  * installation admin
  * site admin
  * user admin
  * logout
* When logged out, the header only appears if the site setting "Always show user bar on public views" is active.

**Comment by kimisgold** [comment]
This is on the `user-bar` branch of omeka-s and the default theme. If all that works, I'll apply the user bar to the rest of the themes for testing.

**Comment by mebrett** [comment]
On branch user-bar and I see the site setting checkbox but there is not a bar across the top on the public views of pages (when logged in and/or with the box checked and logged out)

**Comment by mebrett** [comment]
Seeing it now. It works. 
Some thoughts: 
* the arrow between the install admin and site admin feels like it should present a dropdown. Maybe just a dot instead? 
* Will people think that the edit icon goes to edit the page (which is the behavior on WordPress) rather than the site overall?
<img width="325" alt="screen shot 2017-06-28 at 4 19 13 pm" src="https://user-images.githubusercontent.com/2314070/27658356-bfde6436-5c1d-11e7-8557-218d40e3b973.png">

**Comment by kimisgold** [comment]
The arrow glyph is an easy change. I could also replace the edit icon with more obvious text. It currently goes to the 'site info' edit page, but is there a more useful page to direct administrators torwards?

**Comment by mebrett** [comment]
I feel that because install admin and site admin go to similar places, there might not be a need for the edit button? You can click site admin and get back to the basics for your site, and then go from there to whatever it was you wanted to edit (theme, collecting form, whatever)
