### ISSUE TITLE
Advanced Search block for site pages

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#905]
Once we have the enhanced search capacity in place, our collections site users will want to be able to plant an advanced search form on a site page.

**Comment by sharonmleon** [comment]
Not sure if this warrants a new issue, but being able to alter the label text on that Advanced Search block would be excellent.

**Comment by zerocrates** [comment]
So, that's what I wanted to discuss, as you've mentioned that before.

When you say label text, you mean the labels for each form element, right?

**Comment by sharonmleon** [comment]
Yep. That's what I'm thinking.

**Comment by zerocrates** [comment]
Do you see the same need for the "real" advanced search? (The one linked from the browse page)

This same basic question comes up a few places: we can easily keep tacking options on to blocks, but then those changes only apply within the block.

This is a case where it could be a little hairy to have all those changeable just because there are so many inputs, so there are therefore lots of labels.

What I'd asked about in the past related to this was: is there something in particular you'd want to change just directly? As in, change the default label across all of S? I seem to remember that it's one or two of the labels in particular that you find problematic.

**Comment by sharonmleon** [comment]
That's a great question. I think that the "property" and "class" language doesn't make any sense to end-users. "Field" and "Type"?

**Comment by zerocrates** [comment]
So, the block is implemented, but I continue to be unsure if it's what we really want. If we _really_ just want prose before, we could have that directly as a setting.

(This is just the same "block or setting" question as for the browse headings, but for the broader constellation of search settings we're talking about.)

**Comment by zerocrates** [comment]
More specifically I'm thinking of having each filter be toggleable on/off, a functionality that could easily include a a place to edit the label names, to live alongside the settings for choosing what properties are available, and (possibly) what introductory text to display, all of which would just affect the single current built-in advanced search page for a site.

I'm somewhat concerned that introducing the block and having some settings there splits up the places where a user would configure search unnecessarily (as well as bringing up issues of duplication or differences between the block and "real" versions).

**Comment by zerocrates** [comment]
The block has the further complication that much of the current scripting and styling around the advanced search relies on IDs, which is always problematic in the infinitely repeatable context of the block system.

The filter change I've already introduced allows a module to do much of what I've mentioned already. In particular:

- It can add content above the search (by prepending a partial just consisting of that text). This was previously not possible without CSS trickery or similar because the standard event used wouldn't allow for putting content above.
- It can turn off or rearrange filters.

Paring down the selectable properties might best be done by just another filter. It would still be possible even without that as the event would let a module replace the normal partial with one that used a filtered set of properties. The same is true for changing labels. For both of these it'd be possible to build more of that into the core itself, but I'm not really sure how commonly this will be occurring and therefore whether it merits that kind of more in-depth functionality. (For example, if we think label changing is particularly likely, we could have the labels actually included in the data passed to the event),
