### ISSUE TITLE
Linked resources do not register for search results

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#939]
If you are using a resource - and only a resource - for an element, the value of that resource does not seem to register in search. 

For example, on the sandbox site all of the Sherlock Holmes stories have as their creator the Omeka Resource Item for Arthur Conan Doyle. A simple search for "Doyle" does not return any of these stories, nor does an advanced search for "Creator contains Doyle". 

(Discovered when trying to create a query to populate the item resource for Collecting, could not get just the works where Creator contained Doyle or Creator contained Austen)

**Comment by zerocrates** [comment]
This is correct: you can find Doyle by finding the Person, then looking at the resources that connect to him, but all those connected items won't show up if you just search for Doyle. The reason: the search is looking at text values, and only the Doyle "person" item actually has the text Doyle on it. The others just have a reference to that person.

Trying to fix this could be tricky... it could work in a limited fashion (like only looking for Titles on related items), but even that could get expensive to search: you need not only everything where a Creator value contains "Doyle" as text, you also need everything that has a Creator value pointing to an item that has Doyle in _its_ text... somewhere, perhaps only Title, perhaps anywhere.

The search interface doesn't have any nice way of presenting searches that work on these interconnected records, but the search implementation itself does: you can do a search that gets you all the items that are connected to the Doyle item, by choosing the "resource" search type and giving the item's ID. Probably the only actually usable UI for that would have to give you the Select Item sidebar to choose the item you want to search for connections to.

**Comment by zerocrates** [comment]
In the case of the sandbox, this is a search of all the Doyle-as-Creator items:

http://dev.omeka.org/omeka-s-sandbox/s/tinbox/item?property[2][res][]=124

(124 is the resource number of the Arthur Conan Doyle item.) The specific form of that search would be different on the current version, as the search syntax has changed.

**Comment by mebrett** [comment]
Thanks for the explanation John. I think some version of this is going to have to get worked into the documentation for search, as I expect users will want the workaround.

**Comment by patrickmj** [comment]
Bonus twist of feasibility and expectations -- what if, instead of a linked internal resource, there's an external link to Doyle's URI on DBpedia? That's probably impossible to make work in the search. So, for consistency of expectations, if we think of both the internal and external links as LOD things, I'd vote for not trying to make that kind of search work either internally or externally.

**Comment by zerocrates** [comment]
There is a little oddity to the model in that we actually can store text alongside the resource ID... we _could_ use/abuse this to store a title or identifier or something, but Patrick's point about external resources is worth considering as well... There'd be a case for treating internal resources differently, but it could easily get confusing.

**Comment by pols12** [comment]
Since the dcterms:title value of linked resource is visible on an item page, it is a bit confusing.

I think a good idea would be to consider title of an item linked resource as a literal value of this item while searching.
Also, linked resource could eventually be listed under a search result if this one is returned because of its dcterms:title property.
