### ISSUE TITLE
Consider putting Resources at the top of Site admin bar

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#946]
It seems to me like the first step in site building is defining the resources for the site. If that's accurate, maybe to guide through the workflow "Resources" should be at the top of the navigation, just under Site info.

**Comment by zerocrates** [comment]
I'm somewhat reluctant, for this reason: the Resources or Pool or whatever is something you're likely to set once (or at least a small number of times), whereas Pages is really the meat of the site and the most likely thing you'd be returning to.

The "first step"-ness of the Pool setting is legitimate though, which is why we have it on the Add form.

**Comment by sharonmleon** [comment]
One possibility might be to move the "Item Pool" before the theme pool in the initial tabs for a new site creation. But once that initial pool is set, it seems to me that it can be lower on the navigation than the page creation and menu setting activities.

**Comment by patrickmj** [comment]
Good point about the pages (and navigation) being the most relevant after the pool is created, though I suspect there could be more activity creating the pool than we think (at least that's what I've been discovering).

It might be that the real workflow would be something like creating an item set or sets for a site even before creating the site itself, then when creating the site those will be available at the outset.
